#+AUTHOR: nekosensei
#+TITLE: steins;gem
#+OPTIONS: toc:nil date:nil
#+LATEX_CLASS: book
#+LATEX_CLASS_OPTIONS: [koma,b5paper,oneside,notitlepage]
#+LATEX_HEADER: \usepackage{indentfirst}
#+LATEX_HEADER: \usepackage[T1]{fontenc}
#+LATEX_HEADER: \usepackage[adobe-utopia]{mathdesign}
#+LATEX_HEADER: \usepackage[scaled]{berasans}
#+LATEX_HEADER: \usepackage[scaled]{beramono}
#+LATEX_HEADER: \setlength{\parskip}{1mm}
-----

#+BEGIN_CENTER


/Mad Steins;Gate spoilers are contained within./

/Madoka Magica spoilers also contained within./
#+END_CENTER
-----

#+TOC: headlines 0

* Girl in Blue
** Despair in Ergosphere

*August 2011*

"Oh no! I just wound you! Don't tell me you're broken," cries the
hostage in blue, holding her grandmother's pocket watch and saying
these words for - is it, perhaps, the first time?

/If so, tell me, lone observer: How is it that you've heard it before?/

Well. This time things may be a little different than you remember them.

"So not fair. I've taken extra good care of you and everything."

-----

The hostage has been shot.

Under other circumstances, these words would have made a lot of sense
together. There are many like them. The mad scientist, forever working
to unseat the ruling world order, has just been betrayed by his
friend - well, his casual acquaintance - and delivered into the arms
of the mysterious world shadow government for they are, after all,
bent on total world domination. But our mad scientist is an innocent
young soul, years of wearing his role as an amusing game has warped
his instincts, and, well, there had been one or two untimely
distractions after that text in the supermarket...

But Okabe's mind is not capable of appreciating this fact right
now. It can see only his best friend, tumbling to the floor, lying on
her back in a pool of red - so much red! - still breathing, eyes
gazing up at the ceiling, through the ceiling, to the stars. She does
not cry at the pain; instead, she /smiles/ (how brightly she smiles!)
and reaches up her hand to the sky and


(his own psyche teeters on the edge of its own event horizon. he may
have said something. "what the hell is this?!? you'll pay for this!!"
but he's not quite all there)

the door to the lab splinters, kicked in, its cheap lock no match for
the fury of a skilled warrior. Okabe's mind is still not working, and
it finds itself distracted (now of all times!) by the trivial, the
broken door, his fear of a confrontation with Mr. Braun. A flush of
shame burns his cheeks as he realizes its triviality, but now the dust
has settled and Moeka is pointing a gun at Suzuha on the floor and she
is pointing one back: click-click.

(The warrior understands on a level below conscious thought: /Moeka is
no trained killer, and unused to the adrenaline rush of combat, she
will find it hard to pull the trigger a second time. But the betrayer
might still react if Suzuha were to move suddenly, and if either of
them shoot or of she waits too long the thugs will waste no time
turning the room into a killing zone. She will rely on the gambit,
then, and risk herself --)

"The 42 inch television downstairs. It's on."

The part of Okabe's mind that understood the broken door makes itself
useful, now. The 42 inch television belongs to Mr. Braun. The 42 inch
television acts as a lifter to power the /PhoneWave (Real Name TBD)/. He
can send a D-mail. He can do better than a D-Mail. He can save his
friend -

he lurches towards the computer, unsteady -

another gunshot /(LOUD)/ /(half-deaf)/

the computer is already on (thank God for small favors), screensaver
ends at the click of a button, he puts on the headphones -

another shot, and Kurisu jumps - flies - through the air, shielding him
with her self to buy him the seconds he needs to disable 'test mode'
and initiate the sequence (/I hope to God he was paying attention when
I showed him that/)

but

her body is not enough, the bullet flies on through her shoulder and
strikes the CRT monitor and the glass /implodes/ before his eyes

and he is in terror and he cannot

breathe and

it's all impossible it's wrong how can it /be/ can it /be more wrong/

all his hope be snatched away

and

then, he

hears the impossible scream.

As a would-be mad scientist, Okabe has joked about his hostage's
screams of terror. Indeed, as he played at the classical mad scientist
he would gladly pretend to have /many/ opinions on the topic of
screaming, and also possessed several real opinions on the subject of
maniacal laughter. As a true friend, though, Okabe in fact knows his
hostage's real scream from various misadventures together and the
occasional horror movie. It is a shrill noise, loud enough, but with a
tenuous, wavering quality. Would it be strange to say that he
cherished this scream? for knows of her strength and also her
fragility, cherishes this facet of her too.

Yet even as she fell, struck the floor, Mayuuri did not make a
sound. Her landing, even, was implausibly soft; the short, violent
journey to the doorway of death, impossibly peaceful.

The sound now hurting his ears is shrill, wavering, but impossibly
loud, impossibly long, a terrible scream of /tortured agony/ and
brutal, animal rage. The building shakes, a little. The lights flicker
and go out, fluorescence replaced with a crimson glow of the deepest,
reddest red.

-----

"Grandma?" asks the little girl.

"No, no." says the voice. "Not just yet."

"Oh. I thought for a moment that I had been ... shot. That I was going
to die."

"It's okay. You were shot."

"Oh. It was - it was Moeka, wasn't it."

"Yes."

"So if you're not Grandma," inquires the girl, a little older than she
was a moment ago, "are you an angel?"

The voice laughed. "I would be /honored/ to be called that."

The girl turns to face the voice. "Oh!" she says in surprise. "For
some reason it seemed like you might be very, very old. That's why I
thought you might be Grandma. But you don't look old."

"You weren't wrong, and you weren't quite right either. I am older
than the stars, and I am as young as you."

"You're beautiful."

"Thank you," says the gold-eyed angel.

The girl in the blue dress pauses a moment.

"Why did Moeka shoot me?"

"Well, it's a long story. Much of it is her fault. She shouldn't have
done it. But there are others, too. They wanted to use her to get at
Okabe."

"Oh," says the hostage. "That's sad. I sorta thought we ought to be
friends."

"In a better world, you would be." The angel sighs a weary sigh.

"What's wrong?" asked the girl.

"There are many people to blame for this, Mayuuri. There's Moeka
herself, but she never wanted this. There are very bad people who used
Moeka, too. You can blame them a lot. There are people using the bad
guys, and they're actually trying to make the world a better place,
and it might even work. And these people were good people, once."

The angel pauses.

"Go on," says the hostage, patiently.

"And then there's me, and I'm trying to use the bad people, to help
make good things happen instead of bad things. And that means people
get hurt, and I know that they're going to get hurt. Tonight, the
people getting hurt are you and your friends. I could have stopped
them, but I didn't, because then I couldn't save the other people."

"Oh," said the girl, and paused. "You're an angel. You have to
... save everyone, I guess. I understand."

"And you're too kind," says the angel, looking down at her feet,
ashamed. "And I know you're too kind, that I can tell you everything,
and you'll say it's all okay. And I tell you it anyway."

"Hey now. You're a good person. I can tell. And I know it's not just
because you look pretty. And you care. And you told me. I forgive you."
Mayuuri leans over and gives the weeping angel a hug.

"I know," says the angel, "just as I know that I don't deserve it."

"Well, I would offer an Oopa pillow if I had one," notes the hostage,
"but I don't have one, so it had to be me."

The angel nods. "Of course. Thank you."

They sat quietly a few moments.

"So is this heaven?"

"Oh, no," says the angel. "This is just a vision. I usually can't do
these, but you're a special exception. As a matter of fact, you're not
dead yet, though you are very, very close."

"Oh," says Mayuuri. "Then what am I doing here?"

"I brought you here," says the angel, "for a few reasons. The
immediate one is that you need more time than you have. The one that
is closest to my heart - well - well, we have something in common, you
and I. I once had a friend, a very best friend, who loved me and cared
about me very much, and would do anything to keep me safe. You have
one too."

"Okabe?" inquires the girl. "I know he's a very good friend. I hope
he's okay, and that he doesn't get shot too."

"Your friend is like my friend. He loves you and cares about you very
much. He would throw away his life to save yours, in the blink of an
eye. He would walk through Hell again and again and again. He would
ruin his life for you, many times over."

The girl in the blue dress /blushes/ and looks away.

"That's... stupid. I don't want him to die. Even for me. Why would he
do something like that?"

"Because he cannot bear losing you, and because he would blame himself.
Even when it's not his fault. Oh, he was reckless, yes, but it's more
my fault than it is his fault."

Mayuuri kicks at the ground, but there's not actually anything here
besides these tow, so she kicks the nothing instead.

"You're like him too. You care about your friend a lot, and you would
blame yourself if he got hurt, even though you are /more/ blameless.
You would be very brave for him. You would die for him too, if you had
to. You want to protect him."

"Yes," declares the girl. "I ... I'm just not very good at it. But
he's taken good care of me. And now... I'm about to die, aren't I."

The angel nods.

"There is a way", says the angel.

"How?"

"I'm afraid I can't /tell/ you, not exactly, or it won't work. But I
can help you to the start of the path."

-----

/Your wish has overcome entropy/, begins the creature, but Mayuuri is
already moving, screaming -

-----

The floor is doused in red blood, and the room glows with a red light,
and at the center of it all is Mayuuri, hovering in the air, a foot
above the ground. She is not dressed in her sundress, but a maid
costume, with many frills, a pocket-watch at her side, and it is all
the same red as the blood on the floor.

Okabe is not sure if he's ever seen Mayuuri wear red before. On some
academic level he supposes he probably has, but she favors the light
blue. Maybe once as part of some cosplay?

Her hair is no longer than usual, not at all like the wig she would
use at Queen May's. /(Lone observer, do you remember Queen May's?)/

/(Well, you shouldn't, because it never existed in this version of
Akihabra. Are you cheating? Do you have a save-file editor?)/

And the mad scientist is now very confused, so he calls out.

"May - Mayuuri?"

The cat-girl's ears twitch, and she turns to face him, with a /hiss/.
Okabe jumps back in surprise, and she /pounces/ but not on Okabe, on
the Organization operative behind behind him, just in front of Daru
(who is lying on the floor). Now there is another scream, mixed with
the ugly gurgle of blood.

Suzuha, to her credit, still has her wits about her, her foot against
Moeka's neck, but she is agape.

-----

"I've finally lost it," said Okabe to Daru. The pair of them have
scrambled over to a corner. "None of this is real, is it. They're
going to take me away, to the funny farm."

"Don't say that, dude. If - if that's the case I'm just as screwed as
you are, and I will /not/ look good in a size-84 straitjacket."

The red light faded, and there was a familiar giggling.

The assistant's voice calls out. "May ... Mayuuri? Is that you?"

"Mmm-hmm! You're all better meow. I'll go get Okarin. Okarin!!!"

Drawn by her voice, he stumbles to his feet, still trying to piece
things together. The hostage is still a catgirl maid, but the terrible
/red/ is gone, replaced with sky-blue frills. Mayuuri blue.

Kurisu is whole, but confused. "How are you - what happened? You were
hurt ..."

"Well, Meoweka shot me, but I became a magical girl so I could save
all of you guys!"

Daru stared. "Magical ... catgirl ... Mayuuri? M... m..."

This would prove to be the impetus to get Kurisu back on her
feet. "... Daru, I swear, if you say one word that is less than
perfectly appropriate I will relieve you of your spine. Is that
clear?"

"But we need to get going really soon meow. They might have brought
backup."

"Do we need to take the time machine?" asked Kurisu.

"It's too much. We can't possibly carry it all. Just ... take the
important pieces and ... destroy the rest," declared the mad
scientist. "We'll burn down the lab to destroy the evidence."

"Gather what you can, then," said Suzuha. "I'll go hot-wire a car."

-----

"We've met online before, you and me," said Suzuha, loading the
partially disassembled microwave into the hatchback. "I post as John
Titor. I'm a time traveler."

"I hid my posts in plain sight," revealed the mad scientist...

-----

Suzuha drove the car and explained at the same time.

"By the year 2036, the UN was dissolved amidst a full-out nuclear
war. The Emergency Defense Committee which replaces them immediately
began to stamp out dissent. Democracy is nothing but a memory. People
sleepwalk through their lives, completely devoid of hope. Opposition
is treason... and treason is death. At the heart of the Council's
reign of terror is a shadow organization, the true world government,
pulling the strings. Their ultimate trump card: the time machine.
Their research arm is known to the public as SERN."

"Nuclear war..." said Kurisu, in shock.

The cat-girl-maid took her hand, wordlessly. She contemplating the
empty space in front of her with a distracted, thoughtful look, one
which would have been more characteristic of Okabe.

"A war arranged by the shadow organi- " she paused. "Okay, everyone,
stay calm."

"What's wrong?"

"Enemy ahead. But they don't know we're in a car, so they might
looking for us yet. Just play it cool, don't try to look."

They passed a van, and turned the corner.

"MSY Deliveries?" asked Daru. "But they're all over town..."

Suzuha nodded. "One of the organization's oldest fronts. They do real
deliveries, but there are ties to the Yakuza. I'll take a detour, make
sure they can't follow us. Play it cool."

She slowed, turning the van down an alley - then stopped, and shifted
into reverse.

"Oh... oh, shit."

"What's wrong??"

"totally screwed we're /totally screwed/."

-----

"Maybe we can negotiate! We have a hostage!" Daru looked back to the
trunk, where Moeka was tied up.

"NO!" said Mayuuri. "No hostages. That's /my/ job and I'm not letting
you give it to anybody else. Besides, it's not really her fault."

"Not her fault?" said Kurisu, from the front seat. "How - I mean, I
don't like the idea either, but - Mayuuri, she /shot/ you! By all
rights you should be dead right now, and -"

"No buts. You can tie her up for meow to be safe, but no being
mean. She's not the bad guy here, she's just ... very confused.
Besides, they probably don't really care if she gets hurt."

Suzuha /squealed/ around the corner, and Okabe slammed into
Mayuuri.

"Hey, careful!" said Daru.

"Oof!" said Mayuuri, but she had a distracted look.

"Confound it, woman! Where did you learn to drive?!" exclaimed Okarin.

Suzuha wore a grim expression.  "Right, so guys, I don't know how to
say this - well, no, I mean, I already said we're totally screwed - I
think they followed me."

The black car from the alley swerved around the corner. Its headlights
were still off.

"While I fully concur with the accuracy of your assessment, I'd say
that it runs a little bit on the /obvious/ side of things!"

"No, from 2036."

Kurisu was a little taken aback. "What? How ... I mean, the /physics/
involved; if you change the future ..."

"Yeah the physics involved all work out fine if we're in a closed
timelike curve where we were all /doomed before I started/."

"Oh. Shit." Daru swore.

"Exactly."

Okabe looked out the rear window. The black car was gaining on
them. The driver was a girl with long red hair, and a ponytail - a
young girl, younger than Suzuha. She wore an unsettling smile.

"Looking on the bright side", said Suzuha, "there are a couple of
other unsettling possibilities. For instance right now I'm just
/assuming/ that we're being chased by a robot assassin from the
future. It could be that SERN already has that technology." She
laughed a nervous laugh.

"Robot assassin??!" asked Daru.

"SERN's top enforcers. Incredibly dangerous. They ... don't experience
pain. You can shoot them full of holes and they just don't stop. And
apparently someone has a depraved sense of humor because they all look
like teenage girls." Suzuha ran a red light as she explained.

"Oh, how lovely," said Kurisu, with a nervous tone.

"I'm going to be honest with you," said Suzuha, "most people don't
survive an encounter."

"What is she doing?" asked Okabe, staring.

The pursuer had opened the car door, and placed a hand on the top of
the car. In a single, swift movement, she flipped herself onto the
roof. The car, somehow, kept driving - accelerated, even.

Okabe's mind reached for something to say: an obscure curse, an appeal
to Norse gods, a plea in the name of Science. He found nothing.

A mid-air somersault later, the girl was on the roof.

-----

"Everyone sit tight," said Mayuuri. "I'm going to try and talk to
her."

Suzuha swerved wildly, hoping to shake off the attacker. "No! We can't
let them have it!" She took in her surroundings, made one last turn
onto a bridge over the river.

"Are you out of your mind?!" exclaimed Daru.

/knock knock knock/, went a sound on the driver's window. A muffled
voice came through the glass. "You guys mind stopping?"

"You won't take us alive!" exclaimed Suzuha, pulled the steering
wheel /hard/

the girl flew off the roof and onto the deck of the bridge, but the
rolled over, out of control, on its roof, back upright for a moment
but still flying through the air

smashed a guardrail, and off the

side of the bridge, they

were falling and

"Okarin!" cried Mayuuri, reached for his hand - grabbed it and

*splash*

-----
for a moment all Okarin saw was /red/
-----

The floor is doused in red blood, and the room glows with a red light,
and at the center of it all is Mayuuri, hovering in the air, a foot
above the ground. She is not dressed in her sundress, but a maid
costume, with many frills, a pocket-watch at her side, and it is all
the same red as the blood on the floor.

Okabe has seen Mayuuri wear red before. It wasn't even that long ago.
What he doesn't understand is why he's seeing it again.

The cat-girl's ears twitch, and she turns to face him, with a /hiss/.
Okabe jumps back in surprise, and she /pounces/ but not on Okabe, on
the Organization operative behind behind him, just in front of Daru
(who is lying on the floor). Now there is another scream, mixed with
the ugly gurgle of blood.

Suzuha, to her credit, still has her wits about her, her foot against
Moeka's neck, but she is agape.

-----

"I don't get it," said Okabe. He was less panicked than before, still
a little shaken, but ... it was just surreal, at this point. "How? It
doesn't make sense. Have I actually gone mad?  We were in the car ..."

Daru looked at him funny. "Dude... pull it together. You're way too
calm, and you're kinda scaring me, and - I mean - given what just
happened that takes some doing."

The red light faded, and there was a familiar giggling.

The assistant's voice calls out. "May ... Mayuuri? Is that you?"

"Mmm-hmm! You're all better meow. I'll go get Okarin. Okarin!!! We're
back!"

"Back?"

Kurisu is whole, but confused. "How are you - what happened? You were
hurt ..."

"Well, Meoweka shot me, but I became a magical girl so I could save
all of you guys!"

Daru stared. "Magical ... catgirl ... Mayuuri? M... m..."

"... Daru, I swear, if you say one word that is less than perfectly
appropriate I will relieve you of your spine. Is that clear?"

"But we need to get going really soon meow. There might have some
backup and there are probably more bad guys waiting nearby just in
case one of us tried to escape, so they can give chase."

"Do we need to take the time machine?" asked Kurisu.

"... Just the important parts," said Okabe, pulling himself back
together. "The phone-wave unit. Computer. Headset. We'll find another
monitor."

"Gather what you can, then," said Suzuha. "I'll go hot-wire a car."

"No driving it off a bridge this time, Titor!" exclaimed Okabe.

"... wait, what?" Suzuha froze.

"That's right. I know your game, future-girl. You're a time traveler
from the year 2036. Did you really think you could hide your online
identity from the great Houin Kyouma??!? Your operational security is
no match for my towering intellect! You're just lucky that we're on
the same side."

"/Okarin!/" said Mayuuri. "Be /nice/."

"... right, sorry. The car! We shall converse while we are en route!"

** It Is An Accursed Business

*July 2009*

The transfer student was trying to get out of an awkward conversation.

"Are you protecting her? Just - let me know, and I'll let the matter
drop."

It was a hot July afternoon, several months after the transfer student
had transferred in. School was letting out, and she'd gone up to the
roof: more to find a moment of quiet reflection than anything else,
but it made a fine place to look out over the city for signs of
miasma. The weather this time of year usually meant that she had it to
herself, but today was clearly an exception.

"I told you before, I don't know anything," she replied.

"Yes, well, you were lying then and you're lying now," observed the
busybody, ever-so-politely.

The transfer student closed her eyes, and took a deep breath. Maybe if
she ignored the problem it would just go away.

"I'm sorry, but I know it's true," insisted the interloper.

In lieu of a reply, the other girl fiddled with her ribbon.

"Please. I know ... I know it's probably my fault, but she was ... she
was my best friend." She looked down at the ground - struggling to
maintain her composure.

Homura stopped fidgeting. /Damn it/, she thought. The worst thing is,
she only knows half of what she was missing: not one, but /two/ best
friends, lost forever. It was quite sad.

She sighed quietly. When considered that way, well... she really
should probably say /something/ about it. /It's probably what she
would have wanted,/ considered Homura. /Actually, she would probably
try to have us be friends with each other/.

The idea brought a wave of nostalgia. They /had/ been friends before.
Not for long, and long ago, but it wasn't a bad timeline, really,
before Oriko had messed everything up. How many years had it been?
Best not to think about that one too hard. A meaningless question in
many ways. Forget about it.

But then again, if Hitomi /was/ a friend, well, then, she's someone
worth protecting.

/Okay. Protection. I've still got this./

"I'm not protecting her. I'm protecting /you/. She was my friend too,"
said Homura, deliberately opaque in the phrasing, "and ... well, I'm
sorry for brushing you off, but, it's kind of hard for me to talk
about it."

Hitomi looked up at her with an uncertain expression, not quite sure
what to think. Akemi-san, always cool and collected, was shaking -
just a little - her voice unsteady.

"But, the thing is ... that difficulty ... it's all part and parcel of
the reason I shouldn't tell you. Shizuki-san, please, if you listen to
me at all, remember this. You don't want to know. No good can ever
come of knowing. It is an accursed business, and you should have no
part of it. /Do not seek to understand./ It has brought despair and
ruin to many girls before Sayaka-chan, and it will not stop with
her. One day, it will be the end of me, as well." She took a deep
breath. It came out ... more emotional than she had planned.

Hitomi blinked. "So she is dead, then."

"It was the night she disappeared, the night of the concert - not even
far from the concert. Her corpse? Annihilated. If it helps, I suppose,
you should know that she went out trying to do the right thing,
trying - hell, trying to be a true ally of justice. An exercise in
futility, but she was never one to let that stop her. Stupid girl, but
a brave heart... I'm sorry. I'm no good at eulogies. But you should
think well of her." /And in the name of Kaname Madoka-chan, don't try
to follow in her footsteps/, she added mentally.

"Oh." Hitomi closed her eyes, reflecting. "That's ... thank you,
Akemi-san."

"You may call me Homura, if you like."

"Thank you, then, Homura-san. I guess ... well, it might have been a
little self-centered, but, I was sure, I was almost /completely/ sure,
that it was about Kamijo-chan, and that it was all my fault."

/It/ was /about Kamijo, and it/ was /your fault/, thought Homura. /But
what do you even say to that?/ She reflected a moment.

"It was inevitable," she finally said, just a moment too late.

"... But it was still my fault."

Homura inhaled. "It's not -"

"It's okay," interrupted Hitomi. "You don't ... you don't have to
pretend for my sake, or out of politeness."

/Again/, thought Homura. She'd paused too long, and now she was doing
it /again/, still unsure of what to say. /Am I just that easy to
read?/ /Or am I out of practice? Wow, Homura./ /Two hundred months of
the same conversations and you've forgotten how to talk to real live
people.../ Or ... no, when you got down to it, that was something she
never actually learned to begin with.

"It... it's okay, I'll ... I'll just leave you be, Homura-san."

"Hitomi-san," she called -- but the other girl was already running
off.

-----

Hitomi managed, somehow, /not/ to cry until she had made it to her
locker, and even then only for a bit. At home, though, safely cocooned
in a pile of blankets and pillows, it was another matter.

-----

"Well," said Mami-senpai. "What's done is done, I suppose. At the rate
things are going, it's the last of our problems if she finds out
more. And don't be too hard on yourself. It's not a bad thing to reach
out and try to make a friend, you know. It's pretty lonely these
days."

The other girl pondered. It /was/ pretty empty these days, but she
liked it better empty. Mami always had a bad habit of putting on airs
to impress the less experienced girls - even Kyoko, if only as a
matter of habit. Now, though, there was no reason save the force of
habit to play at being anything but cynical old veterans. It was a
small comfort.

Still, it wouldn't do to say so out loud.

"I did my best to warn her away, at least," said Homura.

A moment later, she started to laugh.

"What?"

"Oh, just - warning her away. Knowing my luck, that means she'll
contract in a month, /maximum/."

"You," said Mami, "are too hard on yourself, as usual. You're not so
unlucky as you say you are. In combat, you're about as good as I am,
and if I may say so myself, that is really /very/ good."

"Being good in a fight means you /don't/ leave /anything/ to luck."

"That .. is true enough," noted Mami.

They looked out over the city in silence, for a moment.

"So, speaking of people who blame themselves for Sayaka, and really
shouldn't," asked Mami, quietly, "where do you think she'd be out
wandering tonight?"

Homura shrugged. "In this heat? Somewhere with a beach, maybe."

-----

The girl with red hair was not very good at wandering in the
wilderness. For a week or three she had managed well enough, but one
day after a mean little fight with some demons (and some girls who
were doing a very bad job of stopping them) she'd gone into a train
station, applied a very small amount of magic to a ticket machine (in
lieu of cash) and found that her magical one-way ticket on the /next
train to anywhere/ was valid for all stations in Kazamino. Call it
fate, perhaps.

So Kyoko went home. At least the local riff-raff would know better
than to mess with her. She didn't mind the fights themselves, and
frightening idiots was always a bit of an adrenaline rush, but badly
hurting them when they kept /throwing themselves at you/, heedless of
their own well-being... that was just depressing. Especially
now. Better to be the legend, the scary girl everyone knew and
avoided, /the Heretic of Kazamino City/. (They had wanted to call her
a demon, but decided it was confusing.)

She disembarked at Kazamino North Station, a run-down part of town
(Kazamino was no Mitakihara, that was certain) filled with old offices
and the occasional warehouse. It was a slightly longer walk, but the
streets would be emptier this way, especially on a weekend.

Eventually she reached the ruins.

When was it she been here last? Was it really with Miki-san? It seemed
recent, and yet so long ago. /This must be what it is to grow old/,
she realized. The neighborhood was looking rougher than it used to be,
trash in the streets, graffiti, ruin inviting neglect. It looks like
one of the corner groceries here had gone out of business, too. A nice
black car, darkened windows, parked in front of an apartment block
across the way, a little out of place. Huh.

The front door had fallen in last visit, hinges detached from the
damaged frame. It lay there on the ground, unmoved. This was only
natural, but still managed to unnerve her. It didn't feel right. Or
maybe...

Hmm. Maybe it didn't feel right because someone else was here.

"Hey! What's the big idea?" she shouted.

The other girl was dressed in white, a nice outfit - Sunday best,
perhaps, blouse trimmed with a bow and lace - seated, hands folded in
her lap, in the front pew. She turned to face Kyoko.

"Oh. I thought this was a place for contemplation," she said. "I'm
sorry. I can leave if I'm bothering you."

Kyoko tilted her head to the side. "Huh. You sure picked a funny
church to come pray."

"I know the history."

"Mmh. Well," replied the red girl, walking forward down the
aisle. "Contemplation, huh. I guess it's still good for that." There
was something about the girl which was bugging her, but she couldn't
quite place it - something besides the fact that she was here to begin
with, that is.

"Do you suppose God is real?" asked the girl in white. "Heaven? I
wonder, sometimes. I could never see what comes after the end."

/Oh/, thought Kyoko, stopping in her tracks, tensing as she recognized
the figure. /It's/ her. /The one with the bucket for a hat./

Kyoko had heard of Oriko more than seen her - usually she'd stay well
away from combat, and it was her team full of murder-psychos that
they'd meet. It was really annoying, because Oriko had precognitive
powers, so her team would always know /exactly when/ another group was
overwhelmed and would swoop in, steal your hard-earned grief cubes,
and occasionally stab magical girls in the face. Hard to sneak up on
someone like that, easy to be ambushed. Through some good fortune, the
Mitakihara Four only had occasional skirmishes, but the trail of
bodies was legendary. Best to stay away, unless you didn't know any
better, which is probably how that little girl ended up with the
group...

And given it was probably her driver who had parked out in front, so,
she might have brought her team, which means this could be her ambush
right here, and -

"Kirika's outside, but I asked her to stay put. I didn't come here to
fight you, Kyoko."

Kyoko exhaled. "What, so you came to talk religion?"

"Is that so strange? We each have what you might call a unique
perspective."

"Hmh. You want unique, you should go back to Mitakihara and talk to
Akemi-san."

"Yes, well, I'm afraid she doesn't trust me. Apparently I hurt one of
her friends in a previous life, I think. She's not very forthcoming
about it, though. She never is."

"I don't exactly trust you either."

"I have a bad habit of unsettling people, I know." She reached into
the back of the pew, pulling out a slightly moldy missal, opened it to
a page in the middle, and began to read. "Death with life contended;
combat, strangely ended. Life's own champion, slain, yet lives to
reign... Angels, there attesting. Shroud, with grave-clothes,
resting. Christ, my hope, has risen."

"Mm. That'd be an Easter sequence. You're a few weeks late."

"You came on Easter, didn't you?"

She had.

"... what's it to you?"

"And on Christmas. I find it strange. Many Christians have left the
church for far less than what you have been through."

"Yeah, well, if you ask the church, we left a while /before/
everything burned to the ground."

"The faithful heretic. A minor miracle. Even at the end of her rope,
she cries out, 'Dear god, please just let me have one happy dream.'"

Kyoko glared.

"I'm sorry, I'm doing it again. I'll try to stop."

"You do that."

"It's a lovely place, though," said Oriko, "even in ruins. Stained
glass, shattered. There's probably a metaphor in that, if you go
looking for it. "

Kyoko sighed. "Actually, when I was little, I always wanted the
windows to be more colorful, with lots of angels on them, but Dad was
skeptical of those kinds of icons - and, of course, it was money,
which we never had, not until the end."

Oriko nodded. "I guess I hadn't considered the theological implications
of architecture."

"Oh, you can tell a lot about a church from that. I did a big report
on it once for the bible study group. The Catholics really love the
stained-glass saints and lots of busy color everywhere, but as you go
north and west with the Reformation and the Protestants they prefer
simple designs on fields of colors, or even just white, and more
geometry. White and wood interiors, too, and the /prettiest/ pipe
organs you ever did see. The eastern churches like to paint their
saints on the ceiling, and if you go to America they have some that
just meet in warehouses, and oh my god why am I telling you -"

"It's okay. I'll listen."

"You know you /really/ don't live up to your reputation as the queen
of the psycho-crazies, Mikuni-san," said Kyoko, just a little bit
exasperated.

"Well, I can't say you're exactly the picture-perfect model of a
juvenile delinquent yourself, Sakura-san."

For the first time in well over a year, laughter echoed through the
church. "Yeah. Yeah, I was a real good little choir girl back in the
day, wasn't I? Almost as sharp a dresser as you, if I'm honest."

-----

She wasn't sure how long they talked, but Oriko left her with a bag of
fresh apples and an open invitation to drop by next time she was in
town. "No need to call ahead," she had noted; "stop by for dinner,
maybe?" Okay, the idea was a little creepy.

Perhaps she would visit in a while anyway. Still, not too soon; maybe
give it a few days, wait until the middle of the week. Besides, in this
weather? Might as well take a little side trip and visit the beach.

-----

/make a contract with me/, said the bunny - cat - thing to the
emotional wreck, leaping onto a very elaborate canopy bed, /and/

** I'm Taking You Away to my Magical Realm
*July 2009*

"Oriko-onee-chan!!!" The little girl in green ran through the hall,
and wrapped her arms around Oriko.

"Ah, Yuma-chan!"

"You're back!"

"Mmm-hmm. Right when I said I'd be back, right?"

Yuma nodded. "Right. It's exactly when. And Kirika is back too."

"Yep. She's gone to her room already."

"Is Hinata-san back yet?" asked Oriko.

"Don't you /knoow/ if she's back?" asked Yuma.

Oriko shook her head No. "I only ever know things that are /going/ to
happen, silly. I don't know everything that's going on right now."

"Well," said Yuma, taking a deep breath, "Aina-senpai got back, and,
and, Miroko-senpai did some magic in the hallway and trapped her in a
giant ice cube and she said, she said, I've got you now, and, I'm
taking you away to my magical realm, and, I'm going to have my way
with ..."

"Oh my," interrupted Oriko, "I hope you stayed out of their way;
that's ... a little bit of trouble."

"Yes! Trouble! The ice cube melted, and, there's a big, big, very big
puddle, alll over the floor."

"Goodness." said Oriko. "That won't do either. I hope you were on
better behavior yourself, though."

"Mmm-hmm!" nodded Yuma, energetically. "I missed you though. Hey did
my magic work?"

"It worked perfectly, of course." She scooped the little girl up in
her arms, for a hug. "You're a magical genius, didn't you know?"

Yuma stuck out her tongue. "You keep saying that, but it's really
really hard."

"Mmm-hmm. Hard work is behind every paragon of excellence in this
world. Hard hard work. You're good at that, and you're really smart,
and you have a /beautiful/ imagination."

Yuma made a face. "Plus I'm super cute."

Oriko nodded. "Plus, you're super cute. And ticklish."

"Noooo!" squealed Yuma. "No tickles."

"Okay, no tickles. Do you want to pick our new story tonight?"

"No, you pick!"

"Oh, okay." Oriko pondered a moment, scanning the shelves. "I have
just the thing. /The Secret Garden/."

-----

Homura was having a bad morning when the delinquent showed up.

"How's it hanging, homu-slice?"

"In the interests of group harmony, I am going to pretend I didn't
hear that, Sakura-san."

It was early in the morning, Kyoko was in the school uniform that she
wore when she was pretending to have business on campus.

"Aww. You're just no fun anymore, Homura."

"We missed you these past weeks," said Homura, as flatly as ever. "We
had speculated that you might have been at the beach."

"I - wait, now how'd you know that?"

"It is no use, Sakura-san. We have your number."

"Are you saying I'm predictable?"

"In the interests of group harmony, I would prefer to phrase it in a
manner that underscores the strength of our working relationship."

"Hey, I'll have you know that I do lots of unpredictable things."

"I'm quite sure. Will you be staying with us for a while, then?"

"I guess? I mean I haven't -"

"Enjoy your stay, then. We'll be starting the hunt from the usual
spot. Let us know in advance if we should wait for you."

Kyoko said nothing.

A few seconds passed.

"... I must admit, you have surprised me here, Kyoko. I would have
predicted another complaint about my attitude."

"Yeah, well, in the interest of group harmony, um, I suppose I can cut
you some slack."

"Thank you. I appreciate it. Despite the facade of a cheery demeanor
that I present the world, I am not having a good morning."

"Right," said Kyoko, pausing. "Anything I can do to make it better?"

"I'd greatly appreciate just talking business for the time being."

"Right. Well, I'll meet you guys at sundown, I guess? I'm a little low
on cubes. Not badly, though. Will grab dinner ahead of time."

"Mmm-hmm."

"Hey, speaking of dinner, how's Team Psycho treating you of late?"

"Better than expected. They're busy bothering everybody else."

"Oh, that's... good, I guess."

"What does that have to do with dinner?"

"Oh, funny story. I went by my old place in Kazamino before the beach,
and who do you think I run into?"

"A takoyaki vendor?" asked Homura.

"Nope! None other but the elusive Mikuni Oriko, herself, in the
flesh. Just sitting around, waiting to talk to me."

Homura took a moment to consider that. "This does not bode well."

"No, it all turns out okay. We talk for a while, she invites me over
to dinner, and of course because it's Oriko she's all like 'just come
whenever, I'll be expecting you, because FORESIGHT.' Anyway, it was
actually a real nice little talk."

"What did you talk about?"

Kyoko grinned. "Architecture."

"No, seriously."

"Seriously architecture. Didn't predict that one, did you?"

Homura tilted her head a bit to the side.

"Religious architecture, if it helps. A comparative study. She got me
to totally nerd out; it was awesome."

"Oriko is bad news," said Homura, carefully, "and is probably up to no
good. If I were you, I'd stay away."

"And what makes you the big expert on who's such bad news?"

"We ... have a history. It's not particularly pleasant. I prefer not
talking about it."

"Sure. I suppose I won't challenge that.  /In the interest of group
harmony./"

"Thank you. I appreciate it."

"But I'm going anyway."

"Why?"

Kyoko signed. "Put yourself in my shoes for a minute, Homura. I mean,
living outside the system is an okay deal for a magical girl. You've
got lots of extra time to hunt, you can do whatever you want, it's
/fun/. But you know what I really miss sometimes? A decent homemade
meal. If there were a way to turn grief cubes into cash, I'd dine out,
but I've got enough problems already. I don't want to be one of those
girls who gets caught emptying ATMs and runs out of cubes in jail."

"Kyoko," said Homura, "I realize that this may sound a little
far-fetched, but I do actually care about your well-being. The Southern
Group is far more dangerous than the police, and Oriko is the worst
of them. Visit at your peril."

"I'm touched," said Kyoko, and only a little sarcastically. "Well,
I'll see you tonight, then, Akemi-san."

"Farewell, Kyoko."

Homura joined the crowd heading into class. It was annoying; she'd
actually arrived a little earlier today, in hopes of avoiding people.
Especially people like ...

"Homura-chan!" called a voice.

/Hitomi is a friend. Madoka would want it that way/, she reminded
herself, taking a moment to breathe.

"Good morning, Shizuki-san. I'm sorry I can't talk, I'm running a
little late," said Homura chan. /Well, she's doing better/, thought
Homura.

"After school, then?"

"I'm afraid I have plans. Another time, maybe," replied Homura,
turning to avoid her.

/Please, Homura-chan,/ thought Hitomi. /It's important./

On the steps to the school, in front of a crowd of a hundred, Akemi
Homura, the calm girl, the coordinated girl, prefecture champion of
the pole vault, spun around too fast, tripped down the stairs, and
planted her face on the concrete sidewalk.

A cry went out from the crowd.

"Whoa!!"

"What the -"

"Is she okay? Call the nurse!"

Hitomi blinked several times. "Akemi ... san?"

"Why... just..." She propped herself up.

-----

/Mami. Can't handle this. Send help./

/What? What's wrong?/ she replied.

"... just /wiped out/ on the stairs!" said a student, rounding the
corner.

/Front of school. Our friend, Shizuki Hitomi./

/Oh my goodness, is she all right?/ asked Mami, already hurrying in
that direction.

/What? No, she's fine, but I need to go put on a show for the nurse's
office./

/I'm not sure I understand/, she said, reaching the front entryway,
and edging her way through a bit of a crowd. She wasn't quite sure
what to expect, but Homura picking herself off the pavement was not
it.

"No, no, I'm fine, I was just startled," said Homura to a mousey
little girl who was crouching beside her.

"Well, just to be safe you should stay put anyway. A concussion is
serious business. I won't have you taking any chances on my watch,"
replied her attendant.

"Ah, Nakihara-san, I think she'll be okay," said Hitomi to the
over-eager health rep. She tentatively walked forward to the pair.

"I don't have a concussion," said Homura. /Spare me/, she sent to
Mami. /I do not need another health representative in my life right
now./

/Are you okay, Homura-chan?/ asked a confused Mami.

/Please, just end me now/, said Homura, glaring up at Hitomi.

Mami looked up at Hitomi, and saw the fluffy white animal now perched
on Hitomi's shoulder. /Oh. Oh!/

/Miss Tomoe, this is Miss Shizuki/, she sent to both girls, /and in
the interest of group harmony, I will leave you two with each other./

/Ah, good morning~/, replied Hitomi, sheepishly.

/Four hours after I warned her/, sent Homura. /Four./

-----

Kyoko was having second thoughts. What if this was a bad idea? An
ambush? /But if they'd wanted an ambush, though/, she thought, /she
could have surprised me at the church./

Still. There was something unsettling about the idea that Oriko would
be /expecting/ her in advance. It was rather like Homura calling her
predictable, except even more so. It was almost a question of free
will.

Actually, it was exactly a question of free will. /Which is something
Dad was always ambivalent about,/ considered Kyoko, moodily. Somehow
the question seemed more real coming from Oriko than from an
omniscient god, though.

/I'm distracted/, she realized, /and I should be keeping an eye out,/
/in case of any surprises./ Was that just the breeze, or was there a
rustling sound in the hedge -

she spun around, transforming, and spied the attacker, but it was too
late, and -

"Gotcha!" said a small voice as Kyoko felt someone grabbing her by the
legs.

"Bwuaua?"

A little girl with green hair had leapt out of the bushes and attached
herself to Kyoko's leg. /Oh, this one/, she thought. What was her name
again? They'd bumped into each other on patrol before. She was pretty
cute, actually.

"Um... hi?"

"Got ya!"

Kyoko sighed, exhaled, de-transformed. "You shouldn't sneak up on
people like that. I could have hurt you by mistake."

"Oriko-onee-chan said it would be all right," declared the girl.

/Of course she did/, thought Kyoko.

"So, uh... Yuma-san, was it?"

"No!!" She shook her head. "Yuma-/chan/."

"So informal!" said Kyoko. "Yuma-chan, then, would you mind, ah,
letting go of my leg?"

Yuma shook her head No. "I've /got/ you now, Kyoko-onee-/chan/," she
declared, "and there is no way to escape my clutches, so I'm, I'm...
I'm taking you away to my magical realm and, and, and, I will have my
way with you." She nodded with satisfaction and smiled.

A flustered Kyoko ran that statement through her mind half a dozen
times, trying to understand the implications. This was the Southern
Group, though, legendary for violence and depravity. And here before
her was a cute little girl, /completely at their mercy/.

"Okay, what the /hell/ have these wierdoes been doing to you in
there?" she cried in outrage. "Listen, Yuma-chan, if those wierdoes
have hurt you -- so help me, if they have so much as laid a /finger/
on you -- I will end them all, and burn this place down to the
ground!"

Yuma let go suddenly and fell on her bottom, aghast.

"Wha.. no! /nooooo!/" She scrambled backwards for a moment, trying to
get to her feet, and in a flash of green had transformed into her
costume. "You won't do /anything/ to Oriko-onee-chan without - without
going through me!"

Kyoko took a moment to blink.

Yuma hissed.

"Whoa, hey, I - I'm sorry, this is some kind of misunderstanding. I'm
sorry!"

"Not as sorry as you're going to be!" retorted the grade-school girl,
pointing her staff at Kyoko. It wasn't very scary looking for a
weapon, a large white fuzzy sphere with a cat-tail on the end of a
stick, almost as ridiculous as her cat-ear bonnet with green pigtails
sticking out. Still, it's generally a mistake to judge a magical girl
harmless on looks alone, and a thing like that, well ...  there was no
telling what it could do; at least you knew what you were getting with
a pointy stick.

/Smooth move, me/, thought Kyoko. /How do I de-escalate this?/
Probably best not to transform.

"Hey, now, let's not fight! Especially out here on the street. I was
just here to visit Oriko!"

"Then why did you say you were going to hurt her?" She pointed the
staff at Kyoko, accusingly.

"It's, uh, hard to explain - well, /normally/ little girls don't hear
things like that, unless someone's doing bad things to them. Where did
you learn to say things like that?"

Yuma stood thinking. A few different thoughts came together in her mind.

"Oh," she said. "I guess... huh. Oriko said it was trouble too."

"Yeah, big trouble. I'm just worried they might have been... doing bad
things to you. Hurting you."

"Oh..." She tensed. "bad things ... no ... not anymore." She looked
up. "Oriko /saved/ me... from bad things." She nodded her head, and
her pigtails wobbled.

"Oh thank /god/," said Kyoko, relaxing. /That would be one nightmare I
didn't need in my life./ "Can I see Oriko, though?"

Yuma pondered briefly.

"Okay, but ... /I'm keeping my eye on you/, Kyoko - onee - /chan!/"

-----


TEMPORARY END. MORE LATER.
