#+AUTHOR: nekosensei
#+TITLE: steins;gem

* Preface and Caution

/Mad Steins;Gate spoilers are contained within./

* Despair in Ergosphere

"Oh no! I just wound you! Don't tell me you're broken," cries the
hostage in blue, holding her grandmother's pocket watch and saying
these words for - is it, perhaps, the first time?

/If so, tell me, lone observer: How is it that you've heard it before?/

Well. This time things may be a little different than you remember them.

"So not fair. I've taken extra good care of you and everything."

** Introduction and Poetry

Tradition dictates that we open the work with introspection and
philosophy. Let us consider a twist, then, on the classic question:
Can a multiverse of diverging world lines be justifiably called
infinite?  We can trivially /imagine/ an infinity of different
configurations, but there is no guarantee that every world which is
possible is real, let alone reachable.

What is the scale and the scope of the possible? Our own universe is
quite finely tuned: a mere half-percent adjustment to the strong
nuclear force would make /carbon/ a precious rare element, and a full
2% would make stars as we know them impossible; our existence is
already an exercise in the arbitrary and ridiculous. Surely then we
ought keep an open mind when it comes to exotic universes. One writer
I know would have you imagine a spacetime with a positive-definite
Reimannian metric, where one can stop or reverse the flow of time
itself by flying about in a clockwork rocket!

In our universe of ridiculous universes, what laws must we find to be
truly immutable?  What mathematics underlies the last bastion of
sanity as our imaginary universes teeter on the madness of seething,
untameable chaos?

Chaos. Order. The progression of order to chaos. Surely, in any set of
laws one can propose, it must remain a fact that there are more ways
to be chaotic than there are to be ordered. Statistics, then, must
rule over all, and the ultimate law of all universes is entropy.

But we must put aside our feeble poetry for now and return to our ship
of fools. Oh, yes, they chase phantoms as before. What will happen, I
wonder, if they catch one?

** Lab Crisis

The hostage has been shot.

Under other circumstances, these words would have made a lot of sense
together. There are many like them. The mad scientist, forever working
to unseat the ruling world order, has just been betrayed by his
friend - well, his casual acquaintance - and delivered into the arms
of the mysterious world shadow government for they are, after all,
bent on total world domination. But our mad scientist is an innocent
young soul, years of wearing his role as an amusing game has warped
his instincts, and, well, there had been one or two untimely
distractions after that text in the supermarket...

But Okabe's mind is not capable of appreciating this fact right
now. It can see only his best friend, tumbling to the floor, lying on
her back in a pool of red - so much red! - still breathing, eyes
gazing up at the ceiling, through the ceiling, to the stars. She does
not cry at the pain; instead, she /smiles/ (how brightly she smiles!)
and reaches up her hand to the sky and


(his own psyche teeters on the edge of its own event horizon. he may
have said something. "what the hell is this?!? you'll pay for this!!"
but he's not quite all there)

the door to the lab splinters, kicked in, its cheap lock no match for
the fury of a skilled warrior. Okabe's mind is still not working, and
it finds itself distracted (now of all times!) by the trivial, the
broken door, his fear of a confrontation with Mr. Braun. A flush of
shame burns his cheeks as he realizes its triviality, but now the dust
has settled and Moeka is pointing a gun at Suzuha on the floor and she
is pointing one back: click-click.

/The warrior understands on a level below conscious thoughts: Moeka is
no trained killer, and unused to the adrenaline rush of combat, she
will find it hard to pull the trigger a second time. But the betrayer
might still react if Suzuha were to move suddenly, and if either of
them shoot or of she waits too long the thugs will waste no time
turning the room into a killing zone. She will rely on the gambit,
then, and risk herself -/

"The 42 inch television downstairs. It's on."

The part of Okabe's mind that understood the broken door makes itself
useful, now. The 42 inch television belongs to Mr. Braun. The 42 inch
television acts as a lifter to power the /PhoneWave (Real Name TBD)/. He
can send a D-mail. He can do better than a D-Mail. He can save his
friend -

he lurches towards the computer, unsteady -

another gunshot /(LOUD)/ /(half-deaf)/

the computer is already on (thank God for small favors), screensaver
ends at the click of a button, he puts on the headphones -

another shot, and Kurisu jumps - flies - through the air, shielding him
with her self to buy him the seconds he needs to disable 'test mode'
and initiate the sequence (/I hope to God he was paying attention when
I showed him that/)

but

her body is not enough, the bullet flies on through her shoulder and
strikes the CRT monitor and the glass /implodes/ before his eyes

and he is in terror and he cannot

breathe and

it's all impossible it's wrong how can it /be/ can it /be more wrong/

all his hope be snatched away

and

then, he

hears the impossible scream.

As a would-be mad scientist, Okabe has of course joked about his
hostage's screams of terror. Indeed, as he played at the classical mad
scientist he would gladly pretend to have /many/ opinions on the topic
of screaming, and also possessed several real opinions on the subject
of maniacal laughter. As a true friend, though, Okabe in fact knows
his hostage's real scream from various misadventures together and the
occasional horror movie. It is a shrill noise, loud enough, but with a
tenuous, wavering quality. Would it be strange to say that he
cherished this scream? for knows of her strength and also her
fragility, cherishes this facet of her too.

Yet even as she fell, struck the floor, Mayuuri did not make a
sound. Her landing, even, was implausibly soft; the short, violent
journey to the doorway of death, impossibly peaceful.

The sound now hurting his ears is shrill, wavering, but impossibly
loud, impossibly long, a terrible scream of /tortured agony/ and
brutal, animal rage. The building shakes, a little. The lights flicker
and go out, fluorescence replaced with a crimson glow of the deepest,
reddest red.


** Serenity

"Grandma?" asks the little girl.

"No, no." says the voice. "Not just yet."

"Oh. I thought for a moment that I had been ... shot. That I was going
to die."

"It's okay. You were shot."

"Oh. It was - it was Moeka, wasn't it."

"Yes."

"So if you're not Grandma," inquires the girl, a little older than she
was a moment ago, "are you an angel?"

The voice laughed. "I would be /honored/ to be called that."

The girl turns to face the voice. "Oh!" she says in surprise. "For
some reason it seemed like you might be very, very old. That's why I
thought you might be Grandma. But you don't look old."

"You weren't wrong, and you weren't quite right either. I am older
than the stars, and I am as young as you."

"You're beautiful."

"Thank you," says the gold-eyed angel.

The girl in the blue dress pauses a moment.

"Why did Moeka shoot me?"

"Well, it's a long story. Of course, much of it is her fault. She
shoudn't have done it. But there are others, too. They wanted to use
her to get at Okabe."

"Oh," says the hostage. "That's sad. I sorta thought we ought to be
friends."

"In a better world, you would be." The angel sighs a weary sigh.

"What's wrong?" asked the girl.

"There are many people to blame for this, Mayuuri. There's Moeka
herself, of course, but she never wanted this. There are very bad
people who used Moeka, too. You can blame them a lot. There are people
using the bad guys, and they're actually trying to make the world a
better place, and it might even work. And these people were good
people, once."

The angel pauses.

"Go on," says the hostage, patiently.

"And then there's me, and I'm trying to use the bad people, to help
make good things happen instead of bad things. And that means people
get hurt, and I know that they're going to get hurt. Tonight, the
people getting hurt are you and your friends. I could have stopped
them, but I didn't, because then I couldn't save the other people."

"Oh," said the girl, and paused. "You're an angel. You have to
... save everyone, I guess. I understand."

"And you're too kind," says the angel, looking down at her feet,
ashamed. "And I know you're too kind, that I can tell you everything,
and you'll say it's all okay. And I tell you it anyway."

"Hey now. You're a good person. I can tell. And I know it's not just
because you look pretty. And you care. And you told me. I forgive you."
Mayuuri leans over and gives the weeping angel a hug.

"I know," says the angel, "just as I know that I don't deserve it."

"Well, I would offer an Oopa pillow if I had one," notes the hostage,
"but I don't have one, so it had to be me."

The angel nods. "Of course. Thank you."

They sat quietly a few moments.

"So is this heaven?"

"Oh, no," says the angel. "This is just a vision. I usually can't do
these, but you're a special exception. As a matter of fact, you're not
dead yet, though you are very, very close."

"Oh," says Mayuuri. "Then what am I doing here?"

"I brought you here," says the angel, "for a few reasons. The
immediate one is that you need more time than you have. The one that
is closest to my heart - well - well, we have something in common, you
and I. I once had a friend, a very best friend, who loved me and cared
about me very much, and would do anything to keep me safe. You have
one too."

"Okabe?" inquires the girl. "I know he's a very good friend. I hope
he's okay, and that he doesn't get shot too."

"Your friend is like my friend. He loves you and cares about you very
much. He would throw away his life to save yours, in the blink of an
eye. He would walk through Hell again and again and again. He would
ruin his life for you, many times over."

The girl in the blue dress *blushes* and looks away.

"That's... stupid. I don't want him to die. Even for me. Why would he
do something like that?"

"Because he cannot bear losing you, and because he would blame himself.
Even when it's not his fault. Oh, he was reckless, yes, but it's more
my fault than it is his fault."

Mayuuri kicks at the ground, but there's not actually anything here
besides these tow, so she kicks the nothing instead.

"You're like him too. You care about your friend a lot, and you would
blame yourself if he got hurt, even though you are /more/ blameless.
You would be very brave for him. You would die for him too, if you had
to. You want to protect him."

"Yes," declares the girl. "I ... I'm just not very good at it. But
he's taken good care of me. And now... I'm about to die, aren't I."

The angel nods.

"There is a way", says the angel.

"How?"

"I'm afraid I can't /tell/ you, not exactly, or it won't work. But I
can help you to the start of the path."


** Lab Observations

/Your wish has overcome entropy,/ begins the creature, but Mayuuri is
already moving, screaming -

** Lab Aftermath

The floor is doused in red blood, and the room glows with a red light,
and at the center of it all is Mayuuri, hovering in the air, a foot
above the ground. She is not dressed in her sundress, but a maid
costume, with many frills, a pocket-watch at her side, and it is all
the same red as the blood on the floor.

Okabe is not sure if he's ever seen Mayuuri wear red before. On some
academic level he supposes he probably has, but she favors the light
blue. Maybe once as part of some cosplay?

Her hair is no longer than usual, not at all like the wig she would
use at Queen May's. /(Lone observer, do you remember Queen May's?)/

/(Well, you shouldn't, because it never existed in this version of
Akihabra. Are you cheating? Do you have a save-file editor?)/

And the mad scientist is now very confused, so he calls out.

"May - Mayuuri?"

The cat-girl's ears twitch, and she turns to face him, with a *hiss*.
Okabe jumps back in surprise, and she /pounces/ but not on Okabe, on
the Organization operative behind behind him, just in front of Daru
(who is lying on the floor). Now there is another scream, mixed with
the ugly gurgle of blood.

Suzuha, to her credit, still has her wits about her, her foot against
Moeka's neck, but she is agape.


* Entropy Divergence

** Lab Evacuation

"I've finally lost it," said Okabe to Daru. The pair of them have
scrambled over to a corner. "None of this is real, is it. They're
going to take me away, to the funny farm."

"Don't say that, dude. If - if that's the case I'm just as screwed as
you are, and I will /not/ look good in a size-84 straitjacket."

The red light faded, and there was a familiar giggling.

The assistant's voice calls out. "May ... Mayuuri? Is that you?"

"Mmm-hmm! You're all better meow. I'll go get Okarin. Okarin!!!"

Drawn by her voice, he stumbles to his feet, still trying to piece
things together. The hostage is still a catgirl maid, but the terrible
/red/ is gone, replaced with sky-blue frills. Mayuuri blue.

Kurisu is whole, but confused. "How are you - what happened? You were
hurt ..."

"Well, Meoweka shot me, but I became a magical girl so I could save
all of you guys!"

Daru stared. "Magical ... catgirl ... mayuuri? M... m..."

This would prove to be the impetus to get Kurisu back on her
feet. "... Daru, I swear, if you say one word that is less than
perfectly appropriate I will relieve you of your spine. Is that
clear?"

"But we need to get going really soon meow. They might have brought
backup."

"Do we need to take the time machine?" asked Kurisu.

"It's too much. We can't possibly carry it all. Just ... take the
important pieces and ... destroy the rest," declared the mad
scientist. "We'll burn down the lab to destroy the evidence."

"Gather what you can, then," said Suzuha. "I'll go hot-wire a car."

** Escape

"We've met online before, you and me," said Suzuha, loading the
partially disassembled microwave into the hatchback. "I post as John
Titor. I'm a time traveller."

"I hid my posts in plain sight," revealed the mad scientist...

** Escape Crisis

Suzuha drove the car and explained at the same time.

"By the year 2036, the UN was dissolved amidst a full-out nuclear
war. The Emergency Defense Committee which replaces them immediately
began to stamp out dissent. Democracy is nothing but a memory. People
sleepwalk through their lives, completely devoid of hope. Opposition
is treason... and treason is death. At the heart of the Council's
reign of terror is a shadow organisation, the true world government,
pulling the strings. Their ultimate trump card: the time machine.
Their research arm is known to the public as SERN."

"Nuclear war..." said Kurisu, in shock.

The cat-girl-maid took her hand, wordlessly. She contemplating the
empty space in front of her with a distracted, thoughtful look, one
which would have been more characteristic of Okabe.

"A war arranged by the shadow organi- " she paused. "Okay, everyone,
stay calm."

"What's wrong?"

"Enemy ahead. But they don't know we're in a car, so they might
looking for us yet. Just play it cool, don't try to look."

They passed a van, and turned the corner.

"MSY Deliveries?" asked Daru. "But they're all over town..."

Suzuha nodded. "One of the organisation's oldest fronts. They do real
deliveries, but there are ties to the Yakuza. I'll take a detour, make
sure they can't follow us. Play it cool."

She slowed, turning the van down an alley - then stopped, and shifted
into reverse.

"Oh... oh, shit."

"What's wrong??"

"totally screwed we're /totally screwed/."

** Chase
"Maybe we can negotiate! We have a hostage!" Daru looked back to the
trunk, where Moeka was tied up.

"NO!" said Mayuuri. "No hostages. That's _my_ job and I'm not letting
you give it to anybody else. Besides, it's not really her fault."

"Not her fault?" said Kurisu, from the front seat. "How - I mean, I
don't like the idea either, but - Mayuuri, she _shot_ you! By all
rights you should be dead right now, and -"

"No buts. You can tie her up for meow to be safe, but no being
mean. She's not the bad guy here, she's just ... very confused.
Besides, they probably don't really care if she gets hurt."

Suzuha *squealed* around the corner, and Okabe slammed into
Mayuuri.

"Hey, careful!" said Daru.

"Oof!" said Mayuuri, but she had a distracted look.

"Confound it, woman! Where did you learn to drive?!" exclaimed Okarin.

Suzuha wore a grim expression.  "Right, so guys, I don't know how to
say this - well, no, I mean, I already said we're totally screwed - I
think they followed me."

The black car from the alley swerved around the corner. Its headlights
were still off.

"While I fully concur with the accuracy of your assessment, I'd say
that it runs a little bit on the _obvious_ side of things!"

"No, from 2036."

Kurisu was a little taken aback. "What? How ... I mean, the _physics_
involved; if you change the future ..."

"Yeah the physics involved all work out fine if we're in a closed
timelike curve where we were all _doomed before I started_."

"Oh. Shit." Daru swore.

"Exactly."

Okabe looked out the rear window. The black car was gaining on
them. The driver was a girl with long red hair, and a ponytail - a
young girl, younger than Suzuha. She wore an unsettling smile.

"Looking on the bright side", said Suzuha, "there are a couple of
other unsettling possibilities. For instance right now I'm just
/assuming/ that we're being chased by a robot assassin from the
future. It could be that SERN already has that technology." She
laughed a nervous laugh.

"Robot assassin??!" asked Daru.

"SERN's top enforcers. Incredibly dangerous. They ... don't experience
pain. You can shoot them full of holes and they just don't stop. And
apparently someone has a depraved sense of humor because they all look
like teenage girls." Suzuha ran a red light as she explained.

"Oh, how lovely," said Kurisu, with a nervous tone.

"I'm going to be honest with you," said Suzuha, "most people don't
survive an encounter."

"What is she doing?" asked Okabe, staring.

The pursuer had opened the car door, and placed a hand on the top of
the car. In a single, swift movement, she flipped herself onto the
roof. The car, somehow, kept driving - accelerated, even.

Okabe's mind reached for something to say: an obscure curse, an appeal
to Norse gods, a plea in the name of Science. He found nothing.

A mid-air somersalt later, the girl was on the roof.

** Escape End

"Everyone sit tight," said Mayuuri. "I'm going to try and talk to
her."

Suzuha swerved wildly, hoping to shake off the attacker. "No! We can't
let them have it!" She took in her surroundings, made one last turn
onto a bridge over the river.

"Are you out of your mind?!" exclaimed Daru.

/knock knock knock/, went a sound on the driver's window. A muffled
voice came through the glass. "You guys mind stopping?"

"You won't take us alive!" exclaimed Suzuha, pulled the steering
wheel *hard*

the girl flew off the roof and onto the deck of the bridge, but the
rolled over, out of control, on its roof, back upright for a moment
but still flying through the air

smashed a guardrail, and off the

side of the bridge, they

were falling and

"Okarin!" cried Mayuuri, reached for his hand and

*splash*

** Lab Observations 2

Ordinary observations do not usually merit the invocation of FTL
communications before being processed and summarized: it's simply
inefficient, and physics is a harsh mistress. Waste not, want not!
However, even a routine contract report (message format TS34507012XX)
goes out directly over FTL channels, as a powerful channel to timeless
hyperspace is already open in these circumstances.

Like other FTL message formats, a contract report opens with a full
four-dimensional reference frame coordinate address. This is a
variable-length code; in our present universe, some 13 billion years
young, it only takes a couple of kilobytes. The FTL communications
node itself, does not experience time; the code in the spacetimestamp
alone preserves the ability to sequence messages over the lifetime of
the universe and construct a reference to the data without the expense
of an infinitely complex computation.

In human teminology, the report went something like this.

"Candidate «Shiina Mayuuri» was identified by a sudden potential spike
on the order of 298\rho coincident with an assault on the building which
she occupied. Observation was immediately dispatched, discovering an
organized crime group. The candidate was confronted with violence by
noncandidate «Kiryu Mokeka» in association with the attackers. The
activation of this emotional bond resulted in an increase in candidate
potential to 380\rho as candidate's body was damaged by small arms
fire. Candidate's body was examined by an associate, ineligible
«Rintarou Okabe», resulting in a potential spike to 701\rho. Violent
confrontation was escalated by noncandidate «Amane Suzuha?» with no
impact on potential, providing an opening in which candidate could be
approached. Due to the anticipated potential harvest and the forecast
of imminent death of candidate's body, an expedited telepathic
approach was applied with level 3 safeguards disabled, consistent
with standards for these candidates."

"«!!!» Candidate interrupted telepathic preamble with nonverbal wish
response expressing concern for her friends. The ensuing resonance
cascade resulted in the collection of realized potential in excess of
the 1e6\psi measurable by instruments as configured. Recommend an audit
to confirm full integrity of Node 1 at earliest viable opportunity."

A full audit would cost most of the potential collected from a very
weak contract - the karmic potential stored in the node being
unsuitable for this this sort of analysis. And the incubator would
keep the channel open for a while, incurring additional expense. But
for over 100,000\psi, and understanding besides? A bargain.

A few seconds later, he added the first follow-up note. "Expedited
soul gem extraction was necessary. Follow-up counselling will be
provided as feasible and further monitoring of anomaly «Shiina
Mayuuri» and her associates will continue. If sympathetic potential
resonance promotes more associates of anomaly «Shiina Mayuuri» to
Candidate the rewards may be substantial."

** Lab Aftermath 2

The floor is doused in red blood, and the room glows with a red light,
and at the center of it all is Mayuuri, hovering in the air, a foot
above the ground. She is not dressed in her sundress, but a maid
costume, with many frills, a pocket-watch at her side, and it is all
the same red as the blood on the floor.

Okabe has seen Mayuuri wear red before. It wasn't even that long ago.
What he doesn't understand is why he's seeing it again.

The cat-girl's ears twitch, and she turns to face him, with a *hiss*.
Okabe jumps back in surprise, and she /pounces/ but not on Okabe, on
the Organization operative behind behind him, just in front of Daru
(who is lying on the floor). Now there is another scream, mixed with
the ugly gurgle of blood.

Suzuha, to her credit, still has her wits about her, her foot against
Moeka's neck, but she is agape.

** Lab Evacuation 2
"I don't get it," said Okabe. He was less panicked than before, but
still shaken. "How? It doesn't make sense. Have I actually gone mad?
We were in the car ..."

Daru looked at him funny. "Dude... pull it together. You're kinda
scaring me, and - I mean - given what just happened that takes some
doing."

The red light faded, and there was a familiar giggling.

The assistant's voice calls out. "May ... Mayuuri? Is that you?"

"Mmm-hmm! You're all better meow. I'll go get Okarin. Okarin!!! We're
back!"

"Back?"

Kurisu is whole, but confused. "How are you - what happened? You were
hurt ..."

"Well, Meoweka shot me, but I became a magical girl so I could save
all of you guys!"

Daru stared. "Magical ... catgirl ... mayuuri? M... m..."

"... Daru, I swear, if you say one word that is less than perfectly
appropriate I will relieve you of your spine. Is that clear?"

"But we need to get going really soon meow. There might have some
backup and there are probably more bad guys waiting nearby just in
case one of us tried to escape, so they can give chase."

"Do we need to take the time machine?" asked Kurisu.

"... Just the important parts," said Okabe, pulling himself back
together. "The phone-wave unit. Computer. Headset. We'll find another
monitor."

"Gather what you can, then," said Suzuha. "I'll go hot-wire a car."

"No driving it off a bridge this time, Titor!" exclaimed Okabe.

"... wait, what?" Suzuha froze.

"That's right. I know your game, future-girl. You're a time traveller
from the year 2036. Did you really think you could hide your online
identity from the great Houin Kyouma??!? Your operational security is
no match for my towering intellect! You're just lucky that we're on
the same side."

"/Okarin!/" said Mayuuri. "Be /nice/."

"... right, sorry. The car! We shall converse while we are en route!"
