#+BEGIN_COMMENT
; hack up org-mode to do italic paragraphs
(setf (nth 4 org-emphasis-regexp-components) 90)
(load-library "org")
(org-mode)
#+END_COMMENT
#+AUTHOR:  nekosensei
#+TITLE:   steins;gem
#+OPTIONS:     toc:nil date:nil
#+LaTeX_CLASS: book
#+LaTeX_CLASS_OPTIONS: [koma,a4paper,oneside,notitlepage]
#+LaTeX_HEADER: \usepackage[T1]{fontenc}
#+LaTeX_HEADER: \usepackage[adobe-utopia]{mathdesign}
#+LaTeX_HEADER: \usepackage[scaled]{berasans}
#+LaTeX_HEADER: \usepackage[scaled]{beramono}
#+LaTeX_HEADER: \setlength{\parskip}{1mm}
-----

#+BEGIN_CENTER

/Mad Steins;Gate spoilers are contained within./

/Madoka Magica spoilers also contained within./

#+END_CENTER

-----

#+Begin_Latex
\pagebreak
#+End_Latex
* Girl in Blue
** Despair in Ergosphere
"Oh no! I just wound you! Don't tell me you're broken," cries the
hostage in blue, holding her grandmother's pocket watch and saying
these words for - is it, perhaps, the first time?

/If so, tell me, lone observer: How is it that you've heard it before?/

Well. This time things may be a little different than you remember them.

"So not fair. I've taken extra good care of you and everything."

*** Introduction and Poetry

Tradition dictates that we open the work with introspection and
philosophy. Let us consider a twist, then, on the classic question:
Can a multiverse of diverging world lines be justifiably called
infinite?  We can trivially /imagine/ an infinity of different
configurations, but there is no guarantee that every world which is
possible is real, let alone reachable.

What is the scale and the scope of the possible? Our own universe is
quite finely tuned: a mere half-percent adjustment to the strong
nuclear force would make /carbon/ a precious rare element, and a full
2% would make stars as we know them impossible; our existence is
already an exercise in the arbitrary and ridiculous. Surely then we
ought keep an open mind when it comes to exotic universes. One writer
I know would have you imagine a spacetime with a positive-definite
Reimannian metric, where one can stop or reverse the flow of time
itself by flying about in a clockwork rocket!

In our universe of ridiculous universes, what laws must we find to be
truly immutable?  What mathematics underlies the last bastion of
sanity as our imaginary universes teeter on the madness of seething,
untameable chaos?

Chaos. Order. The progression of order to chaos. Surely, in any set of
laws one can propose, it must remain a fact that there are more ways
to be chaotic than there are to be ordered. Statistics, then, must
rule over all, and the ultimate law of all universes is entropy.

But we must put aside our feeble poetry for now and return to our ship
of fools. Oh, yes, they chase phantoms as before. What will happen, I
wonder, if they catch one?

*** Lab Crisis

The hostage has been shot.

Under other circumstances, these words would have made a lot of sense
together. There are many like them. The mad scientist, forever working
to unseat the ruling world order, has just been betrayed by his
friend - well, his casual acquaintance - and delivered into the arms
of the mysterious world shadow government for they are, after all,
bent on total world domination. But our mad scientist is an innocent
young soul, years of wearing his role as an amusing game has warped
his instincts, and, well, there had been one or two untimely
distractions after that text in the supermarket...

But Okabe's mind is not capable of appreciating this fact right
now. It can see only his best friend, tumbling to the floor, lying on
her back in a pool of red - so much red! - still breathing, eyes
gazing up at the ceiling, through the ceiling, to the stars. She does
not cry at the pain; instead, she /smiles/ (how brightly she smiles!)
and reaches up her hand to the sky and


(his own psyche teeters on the edge of its own event horizon. he may
have said something. "what the hell is this?!? you'll pay for this!!"
but he's not quite all there)

the door to the lab splinters, kicked in, its cheap lock no match for
the fury of a skilled warrior. Okabe's mind is still not working, and
it finds itself distracted (now of all times!) by the trivial, the
broken door, his fear of a confrontation with Mr. Braun. A flush of
shame burns his cheeks as he realizes its triviality, but now the dust
has settled and Moeka is pointing a gun at Suzuha on the floor and she
is pointing one back: click-click.

/The warrior understands on a level below conscious thoughts: Moeka is
no trained killer, and unused to the adrenaline rush of combat, she
will find it hard to pull the trigger a second time. But the betrayer
might still react if Suzuha were to move suddenly, and if either of
them shoot or of she waits too long the thugs will waste no time
turning the room into a killing zone. She will rely on the gambit,
then, and risk herself -/

"The 42 inch television downstairs. It's on."

The part of Okabe's mind that understood the broken door makes itself
useful, now. The 42 inch television belongs to Mr. Braun. The 42 inch
television acts as a lifter to power the /PhoneWave (Real Name TBD)/. He
can send a D-mail. He can do better than a D-Mail. He can save his
friend -

he lurches towards the computer, unsteady -

another gunshot /(LOUD)/ /(half-deaf)/

the computer is already on (thank God for small favors), screensaver
ends at the click of a button, he puts on the headphones -

another shot, and Kurisu jumps - flies - through the air, shielding him
with her self to buy him the seconds he needs to disable 'test mode'
and initiate the sequence (/I hope to God he was paying attention when
I showed him that/)

but

her body is not enough, the bullet flies on through her shoulder and
strikes the CRT monitor and the glass /implodes/ before his eyes

and he is in terror and he cannot

breathe and

it's all impossible it's wrong how can it /be/ can it /be more wrong/

all his hope be snatched away

and

then, he

hears the impossible scream.

As a would-be mad scientist, Okabe has of course joked about his
hostage's screams of terror. Indeed, as he played at the classical mad
scientist he would gladly pretend to have /many/ opinions on the topic
of screaming, and also possessed several real opinions on the subject
of maniacal laughter. As a true friend, though, Okabe in fact knows
his hostage's real scream from various misadventures together and the
occasional horror movie. It is a shrill noise, loud enough, but with a
tenuous, wavering quality. Would it be strange to say that he
cherished this scream? for knows of her strength and also her
fragility, cherishes this facet of her too.

Yet even as she fell, struck the floor, Mayuuri did not make a
sound. Her landing, even, was implausibly soft; the short, violent
journey to the doorway of death, impossibly peaceful.

The sound now hurting his ears is shrill, wavering, but impossibly
loud, impossibly long, a terrible scream of /tortured agony/ and
brutal, animal rage. The building shakes, a little. The lights flicker
and go out, fluorescence replaced with a crimson glow of the deepest,
reddest red.

*** Serenity

"Grandma?" asks the little girl.

"No, no." says the voice. "Not just yet."

"Oh. I thought for a moment that I had been ... shot. That I was going
to die."

"It's okay. You were shot."

"Oh. It was - it was Moeka, wasn't it."

"Yes."

"So if you're not Grandma," inquires the girl, a little older than she
was a moment ago, "are you an angel?"

The voice laughed. "I would be /honored/ to be called that."

The girl turns to face the voice. "Oh!" she says in surprise. "For
some reason it seemed like you might be very, very old. That's why I
thought you might be Grandma. But you don't look old."

"You weren't wrong, and you weren't quite right either. I am older
than the stars, and I am as young as you."

"You're beautiful."

"Thank you," says the gold-eyed angel.

The girl in the blue dress pauses a moment.

"Why did Moeka shoot me?"

"Well, it's a long story. Of course, much of it is her fault. She
shoudn't have done it. But there are others, too. They wanted to use
her to get at Okabe."

"Oh," says the hostage. "That's sad. I sorta thought we ought to be
friends."

"In a better world, you would be." The angel sighs a weary sigh.

"What's wrong?" asked the girl.

"There are many people to blame for this, Mayuuri. There's Moeka
herself, of course, but she never wanted this. There are very bad
people who used Moeka, too. You can blame them a lot. There are people
using the bad guys, and they're actually trying to make the world a
better place, and it might even work. And these people were good
people, once."

The angel pauses.

"Go on," says the hostage, patiently.

"And then there's me, and I'm trying to use the bad people, to help
make good things happen instead of bad things. And that means people
get hurt, and I know that they're going to get hurt. Tonight, the
people getting hurt are you and your friends. I could have stopped
them, but I didn't, because then I couldn't save the other people."

"Oh," said the girl, and paused. "You're an angel. You have to
... save everyone, I guess. I understand."

"And you're too kind," says the angel, looking down at her feet,
ashamed. "And I know you're too kind, that I can tell you everything,
and you'll say it's all okay. And I tell you it anyway."

"Hey now. You're a good person. I can tell. And I know it's not just
because you look pretty. And you care. And you told me. I forgive you."
Mayuuri leans over and gives the weeping angel a hug.

"I know," says the angel, "just as I know that I don't deserve it."

"Well, I would offer an Oopa pillow if I had one," notes the hostage,
"but I don't have one, so it had to be me."

The angel nods. "Of course. Thank you."

They sat quietly a few moments.

"So is this heaven?"

"Oh, no," says the angel. "This is just a vision. I usually can't do
these, but you're a special exception. As a matter of fact, you're not
dead yet, though you are very, very close."

"Oh," says Mayuuri. "Then what am I doing here?"

"I brought you here," says the angel, "for a few reasons. The
immediate one is that you need more time than you have. The one that
is closest to my heart - well - well, we have something in common, you
and I. I once had a friend, a very best friend, who loved me and cared
about me very much, and would do anything to keep me safe. You have
one too."

"Okabe?" inquires the girl. "I know he's a very good friend. I hope
he's okay, and that he doesn't get shot too."

"Your friend is like my friend. He loves you and cares about you very
much. He would throw away his life to save yours, in the blink of an
eye. He would walk through Hell again and again and again. He would
ruin his life for you, many times over."

The girl in the blue dress *blushes* and looks away.

"That's... stupid. I don't want him to die. Even for me. Why would he
do something like that?"

"Because he cannot bear losing you, and because he would blame himself.
Even when it's not his fault. Oh, he was reckless, yes, but it's more
my fault than it is his fault."

Mayuuri kicks at the ground, but there's not actually anything here
besides these tow, so she kicks the nothing instead.

"You're like him too. You care about your friend a lot, and you would
blame yourself if he got hurt, even though you are /more/ blameless.
You would be very brave for him. You would die for him too, if you had
to. You want to protect him."

"Yes," declares the girl. "I ... I'm just not very good at it. But
he's taken good care of me. And now... I'm about to die, aren't I."

The angel nods.

"There is a way", says the angel.

"How?"

"I'm afraid I can't /tell/ you, not exactly, or it won't work. But I
can help you to the start of the path."

*** Lab Observations

/Your wish has overcome entropy/, begins the creature, but Mayuuri is
already moving, screaming -

*** Lab Aftermath

The floor is doused in red blood, and the room glows with a red light,
and at the center of it all is Mayuuri, hovering in the air, a foot
above the ground. She is not dressed in her sundress, but a maid
costume, with many frills, a pocket-watch at her side, and it is all
the same red as the blood on the floor.

Okabe is not sure if he's ever seen Mayuuri wear red before. On some
academic level he supposes he probably has, but she favors the light
blue. Maybe once as part of some cosplay?

Her hair is no longer than usual, not at all like the wig she would
use at Queen May's. /(Lone observer, do you remember Queen May's?)/

/(Well, you shouldn't, because it never existed in this version of
Akihabra. Are you cheating? Do you have a save-file editor?)/

And the mad scientist is now very confused, so he calls out.

"May - Mayuuri?"

The cat-girl's ears twitch, and she turns to face him, with a *hiss*.
Okabe jumps back in surprise, and she /pounces/ but not on Okabe, on
the Organization operative behind behind him, just in front of Daru
(who is lying on the floor). Now there is another scream, mixed with
the ugly gurgle of blood.

Suzuha, to her credit, still has her wits about her, her foot against
Moeka's neck, but she is agape.

** Entropy Divergence
*** Lab Evacuation

"I've finally lost it," said Okabe to Daru. The pair of them have
scrambled over to a corner. "None of this is real, is it. They're
going to take me away, to the funny farm."

"Don't say that, dude. If - if that's the case I'm just as screwed as
you are, and I will /not/ look good in a size-84 straitjacket."

The red light faded, and there was a familiar giggling.

The assistant's voice calls out. "May ... Mayuuri? Is that you?"

"Mmm-hmm! You're all better meow. I'll go get Okarin. Okarin!!!"

Drawn by her voice, he stumbles to his feet, still trying to piece
things together. The hostage is still a catgirl maid, but the terrible
/red/ is gone, replaced with sky-blue frills. Mayuuri blue.

Kurisu is whole, but confused. "How are you - what happened? You were
hurt ..."

"Well, Meoweka shot me, but I became a magical girl so I could save
all of you guys!"

Daru stared. "Magical ... catgirl ... mayuuri? M... m..."

This would prove to be the impetus to get Kurisu back on her
feet. "... Daru, I swear, if you say one word that is less than
perfectly appropriate I will relieve you of your spine. Is that
clear?"

"But we need to get going really soon meow. They might have brought
backup."

"Do we need to take the time machine?" asked Kurisu.

"It's too much. We can't possibly carry it all. Just ... take the
important pieces and ... destroy the rest," declared the mad
scientist. "We'll burn down the lab to destroy the evidence."

"Gather what you can, then," said Suzuha. "I'll go hot-wire a car."

*** Escape

"We've met online before, you and me," said Suzuha, loading the
partially disassembled microwave into the hatchback. "I post as John
Titor. I'm a time traveller."

"I hid my posts in plain sight," revealed the mad scientist...

*** Escape Crisis

Suzuha drove the car and explained at the same time.

"By the year 2036, the UN was dissolved amidst a full-out nuclear
war. The Emergency Defense Committee which replaces them immediately
began to stamp out dissent. Democracy is nothing but a memory. People
sleepwalk through their lives, completely devoid of hope. Opposition
is treason... and treason is death. At the heart of the Council's
reign of terror is a shadow organisation, the true world government,
pulling the strings. Their ultimate trump card: the time machine.
Their research arm is known to the public as SERN."

"Nuclear war..." said Kurisu, in shock.

The cat-girl-maid took her hand, wordlessly. She contemplating the
empty space in front of her with a distracted, thoughtful look, one
which would have been more characteristic of Okabe.

"A war arranged by the shadow organi- " she paused. "Okay, everyone,
stay calm."

"What's wrong?"

"Enemy ahead. But they don't know we're in a car, so they might
looking for us yet. Just play it cool, don't try to look."

They passed a van, and turned the corner.

"MSY Deliveries?" asked Daru. "But they're all over town..."

Suzuha nodded. "One of the organisation's oldest fronts. They do real
deliveries, but there are ties to the Yakuza. I'll take a detour, make
sure they can't follow us. Play it cool."

She slowed, turning the van down an alley - then stopped, and shifted
into reverse.

"Oh... oh, shit."

"What's wrong??"

"totally screwed we're /totally screwed/."

*** Chase
"Maybe we can negotiate! We have a hostage!" Daru looked back to the
trunk, where Moeka was tied up.

"NO!" said Mayuuri. "No hostages. That's _my_ job and I'm not letting
you give it to anybody else. Besides, it's not really her fault."

"Not her fault?" said Kurisu, from the front seat. "How - I mean, I
don't like the idea either, but - Mayuuri, she _shot_ you! By all
rights you should be dead right now, and -"

"No buts. You can tie her up for meow to be safe, but no being
mean. She's not the bad guy here, she's just ... very confused.
Besides, they probably don't really care if she gets hurt."

Suzuha *squealed* around the corner, and Okabe slammed into
Mayuuri.

"Hey, careful!" said Daru.

"Oof!" said Mayuuri, but she had a distracted look.

"Confound it, woman! Where did you learn to drive?!" exclaimed Okarin.

Suzuha wore a grim expression.  "Right, so guys, I don't know how to
say this - well, no, I mean, I already said we're totally screwed - I
think they followed me."

The black car from the alley swerved around the corner. Its headlights
were still off.

"While I fully concur with the accuracy of your assessment, I'd say
that it runs a little bit on the /obvious/ side of things!"

"No, from 2036."

Kurisu was a little taken aback. "What? How ... I mean, the /physics/
involved; if you change the future ..."

"Yeah the physics involved all work out fine if we're in a closed
timelike curve where we were all /doomed before I started/."

"Oh. Shit." Daru swore.

"Exactly."

Okabe looked out the rear window. The black car was gaining on
them. The driver was a girl with long red hair, and a ponytail - a
young girl, younger than Suzuha. She wore an unsettling smile.

"Looking on the bright side", said Suzuha, "there are a couple of
other unsettling possibilities. For instance right now I'm just
/assuming/ that we're being chased by a robot assassin from the
future. It could be that SERN already has that technology." She
laughed a nervous laugh.

"Robot assassin??!" asked Daru.

"SERN's top enforcers. Incredibly dangerous. They ... don't experience
pain. You can shoot them full of holes and they just don't stop. And
apparently someone has a depraved sense of humor because they all look
like teenage girls." Suzuha ran a red light as she explained.

"Oh, how lovely," said Kurisu, with a nervous tone.

"I'm going to be honest with you," said Suzuha, "most people don't
survive an encounter."

"What is she doing?" asked Okabe, staring.

The pursuer had opened the car door, and placed a hand on the top of
the car. In a single, swift movement, she flipped herself onto the
roof. The car, somehow, kept driving - accelerated, even.

Okabe's mind reached for something to say: an obscure curse, an appeal
to Norse gods, a plea in the name of Science. He found nothing.

A mid-air somersalt later, the girl was on the roof.

*** Escape End

"Everyone sit tight," said Mayuuri. "I'm going to try and talk to
her."

Suzuha swerved wildly, hoping to shake off the attacker. "No! We can't
let them have it!" She took in her surroundings, made one last turn
onto a bridge over the river.

"Are you out of your mind?!" exclaimed Daru.

/knock knock knock/, went a sound on the driver's window. A muffled
voice came through the glass. "You guys mind stopping?"

"You won't take us alive!" exclaimed Suzuha, pulled the steering
wheel *hard*

the girl flew off the roof and onto the deck of the bridge, but the
rolled over, out of control, on its roof, back upright for a moment
but still flying through the air

smashed a guardrail, and off the

side of the bridge, they

were falling and

"Okarin!" cried Mayuuri, reached for his hand and

*splash*

*** Lab Observations 2

Ordinary observations do not usually merit the invocation of FTL
communications before being processed and summarized: it's simply
inefficient, and physics is a harsh mistress. Waste not, want not!
However, even a routine contract report (message format TS34507012XX)
goes out directly over FTL channels, as a powerful channel to timeless
hyperspace is already open in these circumstances.

Like other FTL message formats, a contract report opens with a full
four-dimensional reference frame coordinate address. This is a
variable-length code; in our present universe, some 13 billion years
young, it only takes a couple of kilobytes. The FTL communications
node itself, does not experience time; the code in the spacetimestamp
alone preserves the ability to sequence messages over the lifetime of
the universe and construct a reference to the data without the expense
of an infinitely complex computation.

In human teminology, the report went something like this.

"Candidate «Shiina Mayuuri» was identified by a sudden potential spike
on the order of 298\rho coincident with an assault on the building which
she occupied. Observation was immediately dispatched, discovering an
organized crime group. The candidate was confronted with violence by
noncandidate «Kiryu Mokeka» in association with the attackers. The
activation of this emotional bond resulted in an increase in candidate
potential to 380\rho as candidate's body was damaged by small arms
fire. Candidate's body was examined by an associate, ineligible
«Rintarou Okabe», resulting in a potential spike to 701\rho. Violent
confrontation was escalated by noncandidate «Amane Suzuha?» with no
impact on potential, providing an opening in which candidate could be
approached. Due to the anticipated potential harvest and the forecast
of imminent death of candidate's body, an expedited telepathic
approach was applied with level 3 safeguards disabled, consistent
with standards for these candidates."

"«!!!» Candidate interrupted telepathic preamble with nonverbal wish
response expressing concern for her friends. The ensuing resonance
cascade resulted in the collection of realized potential in excess of
the 1e6\psi measurable by instruments as configured. Recommend an audit
to confirm full integrity of Node 1 at earliest viable opportunity."

A full audit would cost most of the potential collected from a very
weak contract - the karmic potential stored in the node being
unsuitable for this this sort of analysis. And the incubator would
keep the channel open for a while, incurring additional expense. But
for over 100,000\psi, and understanding besides? A bargain.

A few seconds later, he added the first follow-up note. "Expedited
soul gem extraction was necessary. Follow-up counselling will be
provided as feasible and further monitoring of anomaly «Shiina
Mayuuri» and her associates will continue. If sympathetic potential
resonance promotes more associates of anomaly «Shiina Mayuuri» to
Candidate the rewards may be substantial."

*** Lab Aftermath 2

The floor is doused in red blood, and the room glows with a red light,
and at the center of it all is Mayuuri, hovering in the air, a foot
above the ground. She is not dressed in her sundress, but a maid
costume, with many frills, a pocket-watch at her side, and it is all
the same red as the blood on the floor.

Okabe has seen Mayuuri wear red before. It wasn't even that long ago.
What he doesn't understand is why he's seeing it again.

The cat-girl's ears twitch, and she turns to face him, with a *hiss*.
Okabe jumps back in surprise, and she /pounces/ but not on Okabe, on
the Organization operative behind behind him, just in front of Daru
(who is lying on the floor). Now there is another scream, mixed with
the ugly gurgle of blood.

Suzuha, to her credit, still has her wits about her, her foot against
Moeka's neck, but she is agape.

*** Lab Evacuation 2
"I don't get it," said Okabe. He was less panicked than before, but
still shaken. "How? It doesn't make sense. Have I actually gone mad?
We were in the car ..."

Daru looked at him funny. "Dude... pull it together. You're kinda
scaring me, and - I mean - given what just happened that takes some
doing."

The red light faded, and there was a familiar giggling.

The assistant's voice calls out. "May ... Mayuuri? Is that you?"

"Mmm-hmm! You're all better meow. I'll go get Okarin. Okarin!!! We're
back!"

"Back?"

Kurisu is whole, but confused. "How are you - what happened? You were
hurt ..."

"Well, Meoweka shot me, but I became a magical girl so I could save
all of you guys!"

Daru stared. "Magical ... catgirl ... mayuuri? M... m..."

"... Daru, I swear, if you say one word that is less than perfectly
appropriate I will relieve you of your spine. Is that clear?"

"But we need to get going really soon meow. There might have some
backup and there are probably more bad guys waiting nearby just in
case one of us tried to escape, so they can give chase."

"Do we need to take the time machine?" asked Kurisu.

"... Just the important parts," said Okabe, pulling himself back
together. "The phone-wave unit. Computer. Headset. We'll find another
monitor."

"Gather what you can, then," said Suzuha. "I'll go hot-wire a car."

"No driving it off a bridge this time, Titor!" exclaimed Okabe.

"... wait, what?" Suzuha froze.

"That's right. I know your game, future-girl. You're a time traveller
from the year 2036. Did you really think you could hide your online
identity from the great Houin Kyouma??!? Your operational security is
no match for my towering intellect! You're just lucky that we're on
the same side."

"/Okarin!/" said Mayuuri. "Be /nice/."

"... right, sorry. The car! We shall converse while we are en route!"
** Redemption Point
*** Curiosity: Denial

The transfer student was trying to get out of an awkward conversation.

"Are you protecting her? Just - let me know, and I'll let the matter
drop."

It was a hot July afternoon, and as of yet, just a little more than a
year before the lab break-in, and several months after she had
transferred in. School was letting, and she'd gone up to the roof,
more to for a moment of quiet reflection than anything else, but it
made a fine place to look out over the city for signs of miasma. The
weather this time of year usually meant that she had it to herself, as
well, but today was clearly an exception.

"I told you before, I don't know anything," she told the busybody.

"Yes, well, you were lying then and you're lying now."

The transfer student closed her eyes, and took a deep breath. Maybe if
she ignored the problem it would just go away.

"I'm sorry, but I know it's true."

The transfer student fiddled with her ribbon.

"Please. I know ... I know it's probably my fault, but she was ... she
was my best friend." She looked down at the ground - struggling to
maintain her composure.

The other girl stopped fidgeting. /Damn it/, thought Homura. /The
worst thing is, she only knows half of it. Two best friends, lost
forever./ It was, perhaps, one of the saddest parts of the story. And
yet...

"You're right, of course," said Homura. "And you /were/ her friend,
and that means something to me, and I do not blame you for asking.
In fact - I'm sorry for brushing you off. I - I should have said
something. It's... it's hard for me too."

Hitomi looked up at her with an uncertain expression, not quite sure
what to thing. The legendary, impenetrable facade of the cool, calm,
collected Akemi-san, even for a moment, showing a crack?

"But, the thing is ... that makes it even more so. You don't want to
know. No good can come of knowing. It is an accursed business and you
should have no part of it. Do not seek to understand. It has brought
despair and ruin to many girls before her, and it will will not stop
with her. One day, it will be the end of me, as well."

Hitomi blinked. "So she /is/ dead, then."

"It was the night she disappeared, of course, the night of the
concert - not even far from the concert. Her corpse? Annihilated. If
it helps, I suppose, you should know that she went out trying to do
the right thing, trying - /hell/, trying to be a true ally of
justice. An exercise in futility, of course, but she was never one to
let that stop her. Stupid girl, but a brave heart... I'm sorry. I'm no
good at eulogies. But you should think well of her." /And in the name
of Kaname Madoka-chan, don't try to follow in her footsteps/, she
added mentally.

"Oh." Hitomi closed her eyes, reflecting. "That's ... thank you,
Akemi-san."

"You may call me Homura, if you like."

"Thank you, then, Homura-san. I guess ... well, it might have been a
little self-centered, but, I was sure, I was almost /completely/ sure,
that it was about Kamijo-chan, and that it was all my fault."

/Of course it's was about Kamijo, and it/ was /your fault/, thought
Homura. /But what do you even say to that?/ She reflected a moment.

"It was inevitable," she finally said, just a moment too late.

"... But it was still my fault."

Homura inhaled. "It -"

"It's okay. You don't have to pretend for my sake, or out of
politeness."

/Again/, thought Homura. She'd paused too long, and now she was doing
it /again/, still unsure of what to say. /Am I just that easy to
read? Or am I out of practice? Wow, Homura. Two hundred months of
the same conversations and you've forgotten how to talk to real
people... Or ..  no, when you get down to it, I suppose that was
something you never actually learned to begin with./

"It... it's okay, I'll ... I'll just leave you be, Homura-san."

Hitomi managed, somehow, /not/ to cry until she had made it to her
locker, and even then only for a bit. At home, though, safely cocooned
in a pile of blankets and pillows, it was another matter.

*** Before the Hunt
"Well." said Mami-senpai. "What's done is done, I suppose. At the rate
things are going, it's the last of our problems if she finds out
more. And don't be too hard on yourself. It's not a bad thing to reach
out and try to make a friend, you know. It's pretty lonely these
days."

The other girl pondered. It /was/ pretty empty these days, but she
liked it better empty. Mami always had a bad habit of putting on airs
to impress the less experienced girls - even Kyoko, if only as a
matter of habit. Now, though, there was no need to play at being
anything but cynical old veterans.

Still, it wouldn't do to say so out loud.

"I did my best to warn her away, at least," said Homura. A moment
later, she started to laugh.

"What?"

"Oh, just - warning her away. Knowing my luck, that means she'll
contract in a month, /maximum/."

"/You/", said Mami, "are too hard on yourself, as usual. You're not so
unlucky as you say you are. In combat, you're about as good as I am,
and if I may say so myself, that is really /very/ good."

"Being good in fight means you /don't/ leave /anything/ to luck."

"That .. is true enough," noted Mami.

They looked out over the city in silence, for a moment.

"So, speaking of people who blame themselves for Sayaka, and really
shouldn't," asked Mami, quietly, "where do you think she'd be out
wandering tonight?"

Homura shrugged. "In this heat? Somewhere with a beach, maybe."

*** Heresy Rendezvous
The girl with red hair was not very good at wandering in the
wilderness. For a week or three she had managed well enough, but one
day after a mean little fight with some demons (and some girls who
were doing a very bad job of stopping them) she'd gone into a train
station, applied a very small amount of magic to a ticket machine (in
lieu of cash) and found that her magical one-way ticket on the /next
train to anywhere/ was valid for all stations in Kazamino. Call it
fate, perhaps.

So Kyoko went home. At least the local riff-raff would know better
than to mess with her. She didn't mind the fights themselves, and
frightening idiots was always a bit of an adrenaline rush, but badly
hurting them when they kept /throwing themselves at you/, heedless of
their own well-being... that was just depressing. Especially
now. Better to be the legend, the scary girl everyone knew and
avoided, /the Heretic of Kazamino City/. (They had wanted to call her
a demon, but decided it was confusing.)

She disembarked at Kazamino North Station, a run-down part of town
(Kazamino was no Mitakihara, that was certain) filled with old offices
and the occasional warehouse. It was a slightly longer walk, but the
streets would be emptier this way, especially on a weekend.

Eventually she reached the ruins.

When was it she been here last? Was it really with Miki-san? It seemed
recent, and yet so long ago. /This must be what it is to grow old/,
she realized. The neighborhood was looking rougher than it used to be,
trash in the streets, graffiti, ruin inviting neglect. It looks like
one of the corner groceries here had gone out of business, too. A nice
black car, darkened windows, parked in front of an apartment block
across the way, a little out of place. Huh.

The front door had fallen in last visit, hinges detached from the
damaged frame. It lay there on the ground, unmoved. This was only
natural, of course, but still managed to unnerve her. It didn't
feel right. Or maybe...

Hmm. Maybe it didn't feel right because someone else was here.

"Hey! What's the big idea?" she shouted.

The other girl was dressed in white, a nice outfit - Sunday best,
perhaps, blouse trimmed with a bow and lace - seated, hands folded in
her lap, in the front pew. She turned to face Kyoko.

"Oh. I thought this was a place for contemplation," she said. "I'm
sorry. I can leave if I'm bothering you."

Kyoko tilted her head to the side. "Huh. You sure picked a funny
church to come pray."

"I know the history."

"Mmh. Well," replied the red girl, walking forward down the
aisle. "Contemplation, huh. I guess it's still good for that." There
was something about the girl which was bugging her, but she couldn't
quite place it - something besides the fact that she was here to begin
with, that is.

"Do you suppose God is real?" asked the girl in white. "Heaven? I
wonder, sometimes. I could never see what comes after the end."

/Oh/, thought Kyoko, stopping in her tracks, tensing. /It's *her*. The
one with the bucket for a hat./ She'd heard of Oriko more than seen
her - usually she'd stay well away from combat, and it was her team
full of murder-psychos that they'd meet. And it was probably her
driver who had parked out in front, so, she might have brought her
team, which means this could be an ambush, and -

"Kirika's outside, but I asked her to stay put. I didn't come here to
fight you, Kyoko."

Kyoko exhaled. "What, so you came to talk religion?"

"Is that so strange? We each have what you might call a unique
perspective."

"Hmh. You want unique, you should go back to Mitakihara and talk to
miss Akemi."

"Yes, well, I'm afraid she doesn't trust me. Apparently I hurt one of
her friends in a previous life, I /think/. She's not very forthcoming
about it, though. She never is"

"I don't exactly trust you either."

"I have a bad habit of /unsettling/ people, I know." She reached into
the back of the pew, pulling out a slightly moldy missal, opened it to
a page in the middle, and began to read. "Death with life contended;
combat, strangely ended. Life's own champion, slain, yet lives to
reign... Angels, there attesting. Shroud, with grave-clothes,
resting. Christ, my hope, has risen."

"Mm. That'd be an Easter sequence. You're a few weeks late."

"You came on Easter, didn't you?"

She had, of course.

"... what's it to you?"

"And on Christmas. I find it strange. Many Christians have left the
church for far less than what you have been through."

"Yeah, well, if you ask the church, we left a while /before/
everything went down.

"The faithful heretic. A minor miracle. Even at the end of her rope,
she cries out, 'Dear god, please just let me have one happy dream.'"

Kyoko glared.

"I'm sorry, I'm doing it again. I'll try to stop."

"You do that."

"It's a lovely place, though," said Oriko, "even in ruins. Stained
glass, shattered. There's probably a metaphor in that, if you go
looking for it. "

Kyoko sighed. "Actually, when I was little, I always wanted the
windows to be more colorful, with lots of angels on them, but Dad was
skeptical of those kinds of icons - and, of course, it was money,
which we never had, not until the end."

Oriko nodded. "I guess I hadn't considered the theologial implications
of architecture."

"Oh, you can tell a lot about a church from that. I did a big report
on it once for the bible study group. The Catholics really love the
stained-glass saints and lots of busy color everywhere, but as you go
north and west with the Reformation and the Protestants they prefer
simple designs on fields of colors, or even just white, and more
geometry. White and wood interiors, too, and the /prettiest/ pipe
organs you ever did see. The eastern churches like to paint their
saints on the ceiling, and if you go to America they have some that
just meet in warehouses, and oh my god why am I telling you -"

"It's okay. I'll listen."

"You know you /really/ don't live up to your reputation as the queen
of the psycho-crazies, miss Mikuni," said Kyoko, just a /little/ bit
exasperated.

"Well, I can't say you're exactly the picture-perfect model of a
juvenile delinquent yourself, Sakura-san."

For the first time in well over a year, laughter echoed through the
church. "Yeah. Yeah, I was a real good little choir girl back in the
day, wasn't I? Almost as sharp a dresser as you, if I'm honest."

*** Heresy Connection

She wasn't sure how long they talked, but Oriko left her with a bag of
fresh apples and an open invitation to drop by next time she was in
town. "No need to call ahead, of course," she had noted. "Stop by for
dinner, maybe."

Perhaps she /would/ visit in a while. Still, maybe give it a few days,
wait until the middle of the week. Besides, in this weather, she ought
to take some time and visit the beach.

***  Regret and Entropy

/make a contract with me/, said the bunny - cat - thing to the
emotional wreck, /and/
** Probability Convergence
*** Curiosity: Engagement

It had started out as a rather funny office lunch.

"Is this a bloody joke?" asked Dr. Ross.

"An insult," suggested Dr. Luciano.

"Well fine, I'll take it then," said Dr. Smith.

"And dirty your hands?" asked Dr. Luciano.

"Please. While the purchase of a lottery ticket is no doubt an
irrational act with a net negative expected value, a €5 scratch off
ticket most likely has an average value of ... oh, I don't know, at
/least/ two euros, maybe €2.50? Easily worth a few moments' of time
with one's esteemed colleagues." He removed a coin from his pocket,
a €2, and held it up. "How appropriate."

"It's the principle of the thing," said Dr. Luciano. "A question of
intellectual conistency. To play at the social sciences, it is a
question of virtue signalling. Is your reputation as an intellectual
worth no more than the coins in your pocket?"

"Well, bloody hell," said Dr. Smith. "Instant prize, €500."

"You can't be serious," objected Ross.

"In the interest of furthering international fraternity and the
brotherhood of science, I hereby donate this ticket to the Super
Proton Synchrotron team party fund," declared Smith.

"We have a party fund?" asked Ross.

"We do now." He picked up the envelope that it had arrived in. "Now,
the question is, who would have thought send such a thing?" The
envelope was a crisp white, a good quality paper, hand lettered
address in all capitals, crimson red ink. "What on Earth is this
postmark? China?"

"Nippon. Look at the stamp," pointed out Luciano, "and I think it is
rice paper, the envelope."

"Who on Earth sends a scratch-off Euro lottery card to Switzerland
... via Japan?" asked Ross.

"Have you considered the possibility that it was the work of aliens?"

For about a week, aliens invading Earth by sending lottery tickets via
Nippon Post was a running joke. Then on Monday, they got another letter.

"Well this is nice," said Dr. Smith. "We can have a /big/ party."

"Yes, but look," said Ross, "it's addressed to the Super Proton
Synchrotron team, /Extraterrestrial Activities Unit/."

"Aha. Someone from the office, then. How droll." He extracted a small
Swiss knife from his pocket, and set about the business of opening.
"What have we here?" he inquired, after a moment.

"Ah, that is the receipt that you get when you purchase the ticket,"
said Luciano.

"Oh, right. You'd forget I don't play these regularly, listening to
the talk around here." He extracted his phone from a pocket. "Does
anyone know how to check the numbers on one of these?"

"Slow down," said Ross, "the draw isn't until tomorrow."

"How can you tell? Oh, it's on the receipt."

*** Curiosity: Excess
"Sweet mother of Jesus," said Luciano. "That's one hell of a party."

It was a later evening than most in the office (with the exception of
certain experiments) and Dr. Felicia Jannsen, notorious wet blanket -
and programme director - noted the small crowd on her way out. "If you
boys want a party," she said drily, "you can book a proper venue, but
you're not having it in any of my labs."

"I don't think that'll be a problem," said Smith. "That's like
... what, /twenty thousand euro?/"

"That's five numbers matched," noted Ross, "but neither of the Lucky
Stars. Looks like Lucky Dip, registered trademark, wasn't so lucky
after all. Should have been 3 and 12."

"What? You played the lottery? And /won/?" asked the director.

"Never in my life!" said Luciano, and explained the circumstances, the
mysterious letter.

Dr. Jannsen blinked, put down her bag, and pulled out a pile of mail.

"Sweet mother of Jesus," said Luciano. "Another one?"

"You already used 'sweet mother of Jesus'," said Smith. "I'll thank
you to mix it up a little."

Inside the envelope was a simple sheet of plain paper, a short message
in crimson red: the numbers three and twelve, surrounded by a star
outline, and "SORRY", once again in all caps.

"Well that's quite nice," said Ross. "Very symmetrical."

"Is this some kind of a joke?" asked the director.

"... A threat," suggested Luciano.

"Who knows about this?" asked the director.

"Well, we were joking about the last ticket all week, so a lot of
people, but, ah..."

"Right," she said in a deathly calm voice, "if anybody asks, this
ticket was a dud. Got it? This /could/ be a security matter."

"You're thinking Russia or whoever has an agent in Euro Millions?"

"I don't know. Send any more of these" - she held up an envelope -
"directly to me. If it turns out it's nothing, you can have the
party. I'll deal with it tomrrow."

*** Curiosity: Blackmail
On Wednesday morning, shortly before she was going to meet with the
head of security, an express overnight envelope arrived. Inside was a
similar rice-paper envelope, and inside that were the co-orodinates,
dates, times, and magnitudes of several small earthquakes (2.1 to 3.8)
which had not yet happened. On a separate sheet of paper, were the
closing stock prices of the Dow Jones Industrial average, due for late
in the evening.

The director cancelled her meetings and instead spent the day pulling
her hair and watching a USGS feed with the Super Proton Synchrotron
leadership team. When the regular mail arrived in the afternoon, with
another rice paper envelope, no one wanted to be the one open it. They
drew straws, using pencils.

"Fucking hell," said Smith. "It's like one of those Internet crazies
come true. What a nightmare."

"Ah, but take solace, my friend," said Luciano. "Our clarivoyant
emmisary at least has the good sense to contact the world through its
/scientific/ leadership, and to lead with the evidence! We are clearly
dealing with greater wisdom than fools posting on the Internet."

"Imagine if he'd gone to the Americans," said Ross.

"By God's hooks," said Luciano, "that /would/ be a disaster."

"... by which, what now?" asked Smith.

"It is as you requested, I am attempting more variety in my oaths."

"Stop it," said Dr. Jannsen. "I have enough of a headache already."

A moment passed before anyone spoke again.

"So what now?" asked Dr. Smith. "What is the ethical thing to do in
this situation? Our responsibilities to humanity? To the project?"

"You know what? I just want to see some new physics out of it," opined
Ross. "That's what we're supposed to be here for. Isn't it?"

"We've yet to see these proposed technical parameters," noted the
director. "We'll decide tomorrow."

*** Curiosity: Singularity
"Well bloody hell, that's ... that's genius. It /might/ very well just
do it," said Ross, holding up an engineering diagram from a stack.

"It'll mean /months/ of downtime!" objected Smith.

"What is all the rest?" inquired Luciano.

"Looks like about five pages of... control software?" asked Ross. "In
pen?"

"... Hey, look at this." said Dr. Smith. "Notice anything funny?"

"How do you mean?" asked Ross.

"If I didn't know better, I'd swear that you wrote this code. Look at
the gratuitous use of 'tap'. You're the only one in the office with
this kind of monad obsession."

"It's a question of mathematical purity - " said Ross. "Ah. Yes.
I suppose I see what you mean."

"What did he say in the letter?" asked the director, and reached for
the earlier letter. "...  foreknowledge has limits: in particular,
myself. Lottery numbers and lists of facts are easy to copy from the
future, but I am restricted by my ability to comprehend and reproduce
the material. Thus I wish to enlist your assistance, et cetera..."

"Bloody hell," said Ross, "My work has been plaigarized, and I haven't
even done it yet."

"You have already used 'bloody hell' this conversation," noted
Luciano. "What is this foul stench in the air? Is it, perhaps,
hipocrisy?"

"Gentlemen. What's your analysis?" demanded the director.

"Well, I can't be completely sure from just a few sketches," said
Ross, "but if this pans out, we could kiss the tera-electron volt
regime goodbye, and that's just with the current facilities. Five
years and an upgrade to the main loop? We could be on the other side
of the desert and start looking at grand unification energies."

"Bloody hell," said Luciano.
