#+SETUPFILE: setup.xorg

* It Is An Accursed Business

*July 2009*

The transfer student was trying to get out of an awkward conversation.

"Are you protecting her? Just - let me know, and I'll let the matter
drop."

It was a hot July afternoon, several months after the transfer student
had transferred in. School was letting out, and she'd gone up to the
roof: more to find a moment of quiet reflection than anything else,
but it made a fine place to look out over the city for signs of
miasma. The weather this time of year usually meant that she had it to
herself, but today was clearly an exception.

"I told you before, I don't know anything," she replied.

"Yes, well, you were lying then and you're lying now," observed the
busybody, ever-so-politely.

The transfer student closed her eyes, and took a deep breath. Maybe if
she ignored the problem it would just go away.

"I'm sorry, but I know it's true," insisted the interloper.

In lieu of a reply, the other girl fiddled with her ribbon.

"Please. I know ... I know it's probably my fault, but she was ... she
was my best friend." She looked down at the ground - struggling to
maintain her composure.

Homura stopped fidgeting. /Damn it/, she thought. The worst thing is,
she only knows half of what she was missing: not one, but /two/ best
friends, lost forever. It was quite sad.

She sighed quietly. When considered that way, well... she really
should probably say /something/ about it. /It's probably what she
would have wanted,/ considered Homura. /Actually, she would probably
try to have us be friends with each other/.

The idea brought a wave of nostalgia. They /had/ been friends before.
Not for long, and long ago, but it wasn't a bad timeline, really,
before Oriko had messed everything up. How many years had it been?
Best not to think about that one too hard. A meaningless question in
many ways. Forget about it.

But then again, if Hitomi /was/ a friend, well, then, she's someone
worth protecting.

/Okay. Protection. I've still got this./

"I'm not protecting her. I'm protecting /you/. She was my friend too,"
said Homura, deliberately opaque in the phrasing, "and ... well, I'm
sorry for brushing you off, but, it's kind of hard for me to talk
about it."

Hitomi looked up at her with an uncertain expression, not quite sure
what to think. Akemi-san, always cool and collected, was shaking -
just a little - her voice unsteady.

"But, the thing is ... that difficulty ... it's all part and parcel of
the reason I shouldn't tell you. Shizuki-san, please, if you listen to
me at all, remember this. You don't want to know. No good can ever
come of knowing. It is an accursed business, and you should have no
part of it. /Do not seek to understand./ It has brought despair and
ruin to many girls before Sayaka-chan, and it will not stop with
her. One day, it will be the end of me, as well." She took a deep
breath. It came out ... more emotional than she had planned.

Hitomi blinked. "So she is dead, then."

"It was the night she disappeared, the night of the concert - not even
far from the concert. Her corpse? Annihilated. If it helps, I suppose,
you should know that she went out trying to do the right thing,
trying - hell, trying to be a true ally of justice. An exercise in
futility, but she was never one to let that stop her. Stupid girl, but
a brave heart... I'm sorry. I'm no good at eulogies. But you should
think well of her." /And in the name of Kaname Madoka-chan, don't try
to follow in her footsteps/, she added mentally.

"Oh." Hitomi closed her eyes, reflecting. "That's ... thank you,
Akemi-san."

"You may call me Homura, if you like."

"Thank you, then, Homura-san. I guess ... well, it might have been a
little self-centered, but, I was sure, I was almost /completely/ sure,
that it was about Kamijo-chan, and that it was all my fault."

/It/ was /about Kamijo, and it/ was /your fault/, thought Homura. /But
what do you even say to that?/ She reflected a moment.

"It was inevitable," she finally said, just a moment too late.

"... But it was still my fault."

Homura inhaled. "It's not -"

"It's okay," interrupted Hitomi. "You don't ... you don't have to
pretend for my sake, or out of politeness."

/Again/, thought Homura. She'd paused too long, and now she was doing
it /again/, still unsure of what to say. /Am I just that easy to
read?/ /Or am I out of practice? Wow, Homura./ /Two hundred months of
the same conversations and you've forgotten how to talk to real live
people.../ Or ... no, when you got down to it, that was something she
never actually learned to begin with.

"It... it's okay, I'll ... I'll just leave you be, Homura-san."

"Hitomi-san," she called -- but the other girl was already running
off.

-----

Hitomi managed, somehow, /not/ to cry until she had made it to her
locker, and even then only for a bit. At home, though, safely cocooned
in a pile of blankets and pillows, it was another matter.

-----

"Well," said Mami-senpai. "What's done is done, I suppose. At the rate
things are going, it's the last of our problems if she finds out
more. And don't be too hard on yourself. It's not a bad thing to reach
out and try to make a friend, you know. It's pretty lonely these
days."

The other girl pondered. It /was/ pretty empty these days, but she
liked it better empty. Mami always had a bad habit of putting on airs
to impress the less experienced girls - even Kyoko, if only as a
matter of habit. Now, though, there was no reason save the force of
habit to play at being anything but cynical old veterans. It was a
small comfort.

Still, it wouldn't do to say so out loud.

"I did my best to warn her away, at least," said Homura.

A moment later, she started to laugh.

"What?"

"Oh, just - warning her away. Knowing my luck, that means she'll
contract in a month, /maximum/."

"You," said Mami, "are too hard on yourself, as usual. You're not so
unlucky as you say you are. In combat, you're about as good as I am,
and if I may say so myself, that is really /very/ good."

"Being good in a fight means you /don't/ leave /anything/ to luck."

"That .. is true enough," noted Mami.

They looked out over the city in silence, for a moment.

"So, speaking of people who blame themselves for Sayaka, and really
shouldn't," asked Mami, quietly, "where do you think she'd be out
wandering tonight?"

Homura shrugged. "In this heat? Somewhere with a beach, maybe."

-----

The girl with red hair was not very good at wandering in the
wilderness. For a week or three she had managed well enough, but one
day after a mean little fight with some demons (and some girls who
were doing a very bad job of stopping them) she'd gone into a train
station, applied a very small amount of magic to a ticket machine (in
lieu of cash) and found that her magical one-way ticket on the /next
train to anywhere/ was valid for all stations in Kazamino. Call it
fate, perhaps.

So Kyoko went home. At least the local riff-raff would know better
than to mess with her. She didn't mind the fights themselves, and
frightening idiots was always a bit of an adrenaline rush, but badly
hurting them when they kept /throwing themselves at you/, heedless of
their own well-being... that was just depressing. Especially
now. Better to be the legend, the scary girl everyone knew and
avoided, /the Heretic of Kazamino City/. (They had wanted to call her
a demon, but decided it was confusing.)

She disembarked at Kazamino North Station, a run-down part of town
(Kazamino was no Mitakihara, that was certain) filled with old offices
and the occasional warehouse. It was a slightly longer walk, but the
streets would be emptier this way, especially on a weekend.

Eventually she reached the ruins.

When was it she been here last? Was it really with Miki-san? It seemed
recent, and yet so long ago. /This must be what it is to grow old/,
she realized. The neighborhood was looking rougher than it used to be,
trash in the streets, graffiti, ruin inviting neglect. It looks like
one of the corner groceries here had gone out of business, too. A nice
black car, darkened windows, parked in front of an apartment block
across the way, a little out of place. Huh.

The front door had fallen in last visit, hinges detached from the
damaged frame. It lay there on the ground, unmoved. This was only
natural, but still managed to unnerve her. It didn't feel right. Or
maybe...

Hmm. Maybe it didn't feel right because someone else was here.

"Hey! What's the big idea?" she shouted.

The other girl was dressed in white, a nice outfit - Sunday best,
perhaps, blouse trimmed with a bow and lace - seated, hands folded in
her lap, in the front pew. She turned to face Kyoko.

"Oh. I thought this was a place for contemplation," she said. "I'm
sorry. I can leave if I'm bothering you."

Kyoko tilted her head to the side. "Huh. You sure picked a funny
church to come pray."

"I know the history."

"Mmh. Well," replied the red girl, walking forward down the
aisle. "Contemplation, huh. I guess it's still good for that." There
was something about the girl which was bugging her, but she couldn't
quite place it - something besides the fact that she was here to begin
with, that is.

"Do you suppose God is real?" asked the girl in white. "Heaven? I
wonder, sometimes. I could never see what comes after the end."

/Oh/, thought Kyoko, stopping in her tracks, tensing as she recognized
the figure. /It's/ her. /The one with the bucket for a hat./

Kyoko had heard of Oriko more than seen her - usually she'd stay well
away from combat, and it was her team full of murder-psychos that
they'd meet. It was really annoying, because Oriko had precognitive
powers, so her team would always know /exactly when/ another group was
overwhelmed and would swoop in, steal your hard-earned grief cubes,
and occasionally stab magical girls in the face. Hard to sneak up on
someone like that, easy to be ambushed. Through some good fortune, the
Mitakihara Four only had occasional skirmishes, but the trail of
bodies was legendary. Best to stay away, unless you didn't know any
better, which is probably how that little girl ended up with the
group...

And given it was probably her driver who had parked out in front, so,
she might have brought her team, which means this could be her ambush
right here, and -

"Kirika's outside, but I asked her to stay put. I didn't come here to
fight you, Kyoko."

Kyoko exhaled. "What, so you came to talk religion?"

"Is that so strange? We each have what you might call a unique
perspective."

"Hmh. You want unique, you should go back to Mitakihara and talk to
Akemi-san."

"Yes, well, I'm afraid she doesn't trust me. Apparently I hurt one of
her friends in a previous life, I think. She's not very forthcoming
about it, though. She never is."

"I don't exactly trust you either."

"I have a bad habit of unsettling people, I know." She reached into
the back of the pew, pulling out a slightly moldy missal, opened it to
a page in the middle, and began to read. "Death with life contended;
combat, strangely ended. Life's own champion, slain, yet lives to
reign... Angels, there attesting. Shroud, with grave-clothes,
resting. Christ, my hope, has risen."

"Mm. That'd be an Easter sequence. You're a few weeks late."

"You came on Easter, didn't you?"

She had.

"... what's it to you?"

"And on Christmas. I find it strange. Many Christians have left the
church for far less than what you have been through."

"Yeah, well, if you ask the church, we left a while /before/
everything burned to the ground."

"The faithful heretic. A minor miracle. Even at the end of her rope,
she cries out, 'Dear god, please just let me have one happy dream.'"

Kyoko glared.

"I'm sorry, I'm doing it again. I'll try to stop."

"You do that."

"It's a lovely place, though," said Oriko, "even in ruins. Stained
glass, shattered. There's probably a metaphor in that, if you go
looking for it. "

Kyoko sighed. "Actually, when I was little, I always wanted the
windows to be more colorful, with lots of angels on them, but Dad was
skeptical of those kinds of icons - and, of course, it was money,
which we never had, not until the end."

Oriko nodded. "I guess I hadn't considered the theological implications
of architecture."

"Oh, you can tell a lot about a church from that. I did a big report
on it once for the bible study group. The Catholics really love the
stained-glass saints and lots of busy color everywhere, but as you go
north and west with the Reformation and the Protestants they prefer
simple designs on fields of colors, or even just white, and more
geometry. White and wood interiors, too, and the /prettiest/ pipe
organs you ever did see. The eastern churches like to paint their
saints on the ceiling, and if you go to America they have some that
just meet in warehouses, and oh my god why am I telling you -"

"It's okay. I'll listen."

"You know you /really/ don't live up to your reputation as the queen
of the psycho-crazies, Mikuni-san," said Kyoko, just a little bit
exasperated.

"Well, I can't say you're exactly the picture-perfect model of a
juvenile delinquent yourself, Sakura-san."

For the first time in well over a year, laughter echoed through the
church. "Yeah. Yeah, I was a real good little choir girl back in the
day, wasn't I? Almost as sharp a dresser as you, if I'm honest."

-----

She wasn't sure how long they talked, but Oriko left her with a bag of
fresh apples and an open invitation to drop by next time she was in
town. "No need to call ahead," she had noted; "stop by for dinner,
maybe?" Okay, the idea was a little creepy.

Perhaps she would visit in a while anyway. Still, not too soon; maybe
give it a few days, wait until the middle of the week. Besides, in this
weather? Might as well take a little side trip and visit the beach.

-----

/make a contract with me/, said the bunny - cat - thing to the
emotional wreck, leaping onto a very elaborate canopy bed, /and/
