#+SETUPFILE: setup.xorg

*Author's Note*: If you are among my approximately-2 readers who read
this story in its pre-release state: chapters 1 and 2 have been
combined and chapter 3 is now chapter 2, with a little extra on
the end.

* I'm Taking You Away to my Magical Realm
*July 2009*

"Oriko-onee-chan!!!" The little girl in green ran through the hall,
and wrapped her arms around Oriko.

"Ah, Yuma-chan!"

"You're back!"

"Mmm-hmm. Right when I said I'd be back, right?"

Yuma nodded. "Right. It's exactly when. And Kirika is back too."

"Yep. She's gone to her room already."

"Is Hinata-san back yet?" asked Oriko.

"Don't you /knoow/ if she's back?" asked Yuma.

Oriko shook her head No. "I only ever know things that are /going/ to
happen, silly. I don't know everything that's going on right now."

"Well," said Yuma, taking a deep breath, "Aina-senpai got back, and,
and, Miroko-senpai did some magic in the hallway and trapped her in a
giant ice cube and she said, she said, I've got you now, and, I'm
taking you away to my magical realm, and, I'm going to have my way
with ..."

"Oh my," interrupted Oriko, "I hope you stayed out of their way;
that's ... a little bit of trouble."

"Yes! Trouble! The ice cube melted, and, there's a big, big, very big
puddle, alll over the floor."

"Goodness." said Oriko. "That won't do either. I hope you were on
better behavior yourself, though."

"Mmm-hmm!" nodded Yuma, energetically. "I missed you though. Hey did
my magic work?"

"It worked perfectly, of course." She scooped the little girl up in
her arms, for a hug. "You're a magical genius, didn't you know?"

Yuma stuck out her tongue. "You keep saying that, but it's really
really hard."

"Mmm-hmm. Hard work is behind every paragon of excellence in this
world. Hard hard work. You're good at that, and you're really smart,
and you have a /beautiful/ imagination."

Yuma made a face. "Plus I'm super cute."

Oriko nodded. "Plus, you're super cute. And ticklish."

"Noooo!" squealed Yuma. "No tickles."

"Okay, no tickles. Do you want to pick our new story tonight?"

"No, you pick!"

"Oh, okay." Oriko pondered a moment, scanning the shelves. "I have
just the thing. /The Secret Garden/."

-----

Homura was having a bad morning when the delinquent showed up.

"How's it hanging, homu-slice?"

"In the interests of group harmony, I am going to pretend I didn't
hear that, Sakura-san."

It was early in the morning, Kyoko was in the school uniform that she
wore when she was pretending to have business on campus.

"Aww. You're just no fun anymore, Homura."

"We missed you these past weeks," said Homura, as flatly as ever. "We
had speculated that you might have been at the beach."

"I - wait, now how'd you know that?"

"It is no use, Sakura-san. We have your number."

"Are you saying I'm predictable?"

"In the interests of group harmony, I would prefer to phrase it in a
manner that underscores the strength of our working relationship."

"Hey, I'll have you know that I do lots of unpredictable things."

"I'm quite sure. Will you be staying with us for a while, then?"

"I guess? I mean I haven't -"

"Enjoy your stay, then. We'll be starting the hunt from the usual
spot. Let us know in advance if we should wait for you."

Kyoko said nothing.

A few seconds passed.

"... I must admit, you have surprised me here, Kyoko. I would have
predicted another complaint about my attitude."

"Yeah, well, in the interest of group harmony, um, I suppose I can cut
you some slack."

"Thank you. I appreciate it. Despite the facade of a cheery demeanor
that I present the world, I am not having a good morning."

"Right," said Kyoko, pausing. "Anything I can do to make it better?"

"I'd greatly appreciate just talking business for the time being."

"Right. Well, I'll meet you guys at sundown, I guess? I'm a little low
on cubes. Not badly, though. Will grab dinner ahead of time."

"Mmm-hmm."

"Hey, speaking of dinner, how's Team Psycho treating you of late?"

"Better than expected. They're busy bothering everybody else."

"Oh, that's... good, I guess."

"What does that have to do with dinner?"

"Oh, funny story. I went by my old place in Kazamino before the beach,
and who do you think I run into?"

"A takoyaki vendor?" asked Homura.

"Nope! None other but the elusive Mikuni Oriko, herself, in the
flesh. Just sitting around, waiting to talk to me."

Homura took a moment to consider that. "This does not bode well."

"No, it all turns out okay. We talk for a while, she invites me over
to dinner, and of course because it's Oriko she's all like 'just come
whenever, I'll be expecting you, because FORESIGHT.' Anyway, it was
actually a real nice little talk."

"What did you talk about?"

Kyoko grinned. "Architecture."

"No, seriously."

"Seriously architecture. Didn't predict that one, did you?"

Homura tilted her head a bit to the side.

"Religious architecture, if it helps. A comparative study. She got me
to totally nerd out; it was awesome."

"Oriko is bad news," said Homura, carefully, "and is probably up to no
good. If I were you, I'd stay away."

"And what makes you the big expert on who's such bad news?"

"We ... have a history. It's not particularly pleasant. I prefer not
talking about it."

"Sure. I suppose I can leave that be. /In the interest of group
harmony./"

"Thank you. I appreciate it."

"But I'm going anyway."

"Why?"

Kyoko signed. "Put yourself in my shoes for a minute, Homura. I mean,
living outside the system is an okay deal for a magical girl. You've
got lots of extra time to hunt, you can do whatever you want, it's
/fun/. But you know what I really miss sometimes? A decent homemade
meal. If there were a way to turn grief cubes into cash, I'd dine out,
but I've got enough problems already. I don't want to be one of those
girls who gets caught emptying ATMs and runs out of cubes in jail."

"Kyoko," said Homura, "I realize that this may sound a little
far-fetched, but I do actually care about your well-being. The Southern
Group is far more dangerous than the police, and Oriko is the worst
of them. Visit at your peril."

"I'm touched," said Kyoko, and only a little sarcastically. "Well,
I'll see you tonight, then, Akemi-san."

"Farewell, Kyoko."

Homura joined the crowd heading into class. It was annoying; she'd
actually arrived a little earlier today, in hopes of avoiding people.
Especially people like ...

"Homura-chan!" called a voice.

/Hitomi is a friend. Madoka would want it that way/, she reminded
herself, taking a moment to breathe.

"Good morning, Shizuki-san. I'm sorry I can't talk, I'm running a
little late," said Homura, carefully avoiding eye contact. /Well,
she's doing better/, thought Homura.

"After school, then?"

"I'm afraid I have plans. Another time, maybe," replied Homura,
turning to avoid her.

/Please, Homura-chan/, thought Hitomi. /It's important./

On the steps to the school, in front of a crowd of a hundred, Akemi
Homura, the calm girl, the coordinated girl, prefecture champion of
the pole vault, spun around too fast, tripped down the stairs, and
planted her face on the concrete sidewalk.

A cry went out from the crowd.

"Whoa!!"

"What the -"

"Is she okay? Call the nurse!"

Hitomi blinked several times. "Akemi ... san?"

"Why... just..." She propped herself up.

-----

/Mami. Can't handle this. Send help./

/What? What's wrong?/ she replied.

"... just /wiped out/ on the stairs!" said a student, rounding the
corner.

/Front of school. Our friend, Shizuki Hitomi./

/Oh my goodness, is she all right?/ asked Mami, already hurrying in
that direction.

/What? No, she's fine, but I need to go put on a show for the nurse's
office./

/I'm not sure I understand/, she said, reaching the front entryway,
and edging her way through a bit of a crowd. She wasn't quite sure
what to expect, but Homura picking herself off the pavement was not
it.

"No, no, I'm fine, I was just startled," said Homura to a mousey
little girl who was crouching beside her.

"Well, just to be safe you should stay put anyway. A concussion is
serious business. I won't have you taking any chances on my watch,"
replied her attendant.

"Ah, Nakihara-san, I think she'll be okay," said Hitomi to the
over-eager health rep. She tentatively walked forward to the pair.

"I don't have a concussion," said Homura. /Spare me/, she sent to
Mami. /I do not need another health representative in my life right
now./

/Are you okay, Homura-chan?/ asked a confused Mami.

/Please, just end me now/, said Homura, glaring up at Hitomi.

Mami looked up at Hitomi, and saw the fluffy white animal now perched
on Hitomi's shoulder. /Oh. Oh!/

/Miss Tomoe, this is Miss Shizuki/, she sent to both girls, /and in
the interest of group harmony, I will leave you two with each other./

/Ah, good morning~/, replied Hitomi, sheepishly.

/Four hours after I warned her/, sent Homura. /Four./

-----

Kyoko was having second thoughts. What if this was a bad idea? An
ambush? /But if they'd wanted an ambush, though/, she thought, /she
could have surprised me at the church./

Still. There was something unsettling about the idea that Oriko would
be /expecting/ her in advance. It was rather like Homura calling her
predictable, except even more so. It was almost a question of free
will.

Actually, it was exactly a question of free will.
/Which is something Dad was always ambivalent about/,
considered Kyoko, moodily. Somehow the question seemed more
real coming from Oriko than from an omniscient god, though.

/I'm distracted/, she realized, /and I should be keeping an eye out/
/in case of any surprises./ Was that just the breeze, or was there a
rustling sound in the hedge -

she spun around, transforming, and spied the attacker, but it was too
late, and -

"Gotcha!" said a small voice as Kyoko felt someone grabbing her by the
legs.

"Bwuaua?"

A little girl with green hair had leapt out of the bushes and attached
herself to Kyoko's leg. /Oh, this one/, she thought. What was her name
again? They'd bumped into each other on patrol before. She was pretty
cute, actually.

"Um... hi?"

"Got ya!"

Kyoko sighed, exhaled, de-transformed. "You shouldn't sneak up on
people like that. I could have hurt you by mistake."

"Oriko-onee-chan said it would be all right," declared the girl.

/Of course she did/, thought Kyoko.

"So, uh... Yuma-san, was it?"

"No!!" She shook her head. "Yuma - /chan/."

"So informal!" said Kyoko. "Yuma-chan, then, would you mind, ah,
letting go of my leg?"

Yuma shook her head No. "I've /got/ you now, Kyoko - onee - /chan/,"
she declared with a bit of a sing-song voice, "and there is no way to
escape my clutches, so I'm, I'm...  I'm taking you away to my magical
realm and, and, and, I will have my way with you." She concluded this
little performance with a nod of satisfaction and a smile.

A flustered Kyoko ran that statement through her mind half a dozen
times, trying to understand the implications. This was the Southern
Group, though, legendary for violence and depravity. And here before
her was a cute little girl, /completely at their mercy/ ...

/This is not good./

"Okay, what the /hell/ have these wierdoes been doing to you in
there?" she cried in outrage. "Listen, Yuma-chan, if those wierdoes
have hurt you -- so help me, if they have so much as laid a /finger/
on you -- I will end them all, and burn this place down to the
ground!"

Yuma let go suddenly and fell on her bottom, aghast.

"Wha.. no! /nooooo!/" She scrambled backwards for a moment, trying to
get to her feet, and in a flash of green had transformed into her
costume. "You won't do /anything/ to Oriko-onee-chan without - without
going through me!"

Kyoko took a moment to blink.

Yuma hissed.

"Whoa, hey, I - I'm sorry, this is some kind of misunderstanding. I'm
sorry!"

"Not as sorry as you're going to be!" retorted the grade-school girl,
pointing her staff at Kyoko. It wasn't very scary looking for a
weapon, a large white fuzzy sphere with a cat-tail on the end of a
stick, almost as ridiculous as her cat-ear bonnet with green pigtails
sticking out. Still, it's generally a mistake to judge a magical girl
harmless on looks alone, and a thing like that, well ...  there was no
telling what it could do; at least you knew what you were getting with
a pointy stick.

/Smooth move, me/, thought Kyoko. /How do I de-escalate this?/
Probably best not to transform.

"Hey, now, let's not fight! Especially out here on the street. I was
just here to visit Oriko!"

"Then why did you say you were going to hurt her?" She pointed the
staff at Kyoko, accusingly.

"It's, uh, hard to explain - well, /normally/ little girls don't hear
things like that, unless someone's doing bad things to them. Where did
you learn to say things like that?"

Yuma stood thinking. A few different thoughts came together in her mind.

"Oh," she said. "I guess... huh. Oriko said it was trouble too."

"Yeah, big trouble. I'm just worried they might have been... doing bad
things to you. Hurting you."

"Oh..." She tensed. "bad things ... no ... not anymore." She looked
up. "Oriko /saved/ me... from bad things." She nodded her head, and
her pigtails wobbled.

"Oh thank /god/," said Kyoko, relaxing. /That would be one nightmare I
didn't need in my life./ "Can I see Oriko, though?"

Yuma pondered briefly.

"Okay, but ... /I'm keeping my eye on you/, Kyoko - onee - /chan!/"

-----

Oriko was waiting in the garden when Yuma opened the gate.

"Watch out!" declared the little girl. "This one is Trouble."

"Oh goodness," said Oriko, pouring some tea. "Was there a slight
misunderstanding?"

"Yeah, something like that," said Kyoko. "Bet you saw it coming, too,
didn'tcha? Real funny."

"While I am guilty as charged," said Oriko, setting down the teapot,
"I assure you that it is nothing to laugh about."

"Uh-huh. Mind giving me an explanation, then?"

"In just a moment," said Oriko. "First, though, there is a small
matter to attend to."

"Oh yeah, what's that?"

"Yuma-chan, if you will?"

Yuma fished around in a pocket, withdrawing a weathered old skeleton
key. With a reverent gesture, she carefully inserted it into the iron
garden gate, closed her eyes, and turned it shut. A shimmer of green
filled the air around them, magical energies tracing their way along
the rosebushes of the garden wall, leaping into the sky to draw, in
ethereal colors, a shifting mosaic of flower outlines in the sky.

"... Huh. Now that's real pretty," observed Kyoko.

"As an explanation," said Oriko, "this is Yuma-chan's magical realm."

"Oh." She looked around. Not just the sky, but everything seemed just
a little more magical. The wrought-iron garden chairs, already fancy,
had turned to ivory and gold, and the scent of the roses was... not
stronger, but somehow more exquisite, elaborate. Magical.

"It's a secret garden," explained Yuma. "It's for telling secrets."

"Secrets?"

"While we are in here, we have absolute privacy," explained Oriko. "No
recording devices will work. No magic can see what we are doing. Even
Kyubey cannot materialize here. One could force their way in, yes, but
we could tell. Speaking of which," she turned to Yuma. "Yuma-chan, my
dear, would you mind stepping away for a bit?"

"But - but - I just /got/ her here!" objected Yuma.

"Sakura-san might have occasion to call me things that a young lady
shouldn't hear. Besides, there will be plenty of time for you two to
play later, I promise."

"Hmmph. There'd better be!" she declared, marching off.

"Now. Won't you have some donabe?" inquired Oriko.

Kyoko sat down, helping herself to some food. "Privacy, huh? Sounds
handy, but, uh, it's a little paranoid, isn't it?"

"Oh, no, not in the least," said Oriko. "The Incubators have been such
/terrible/ busybodies. Besides that, there's a magical girl who keeps
spying on people's conversations, usually before they even
happen. Even when she's in the conversation herself, later. Quite a
bother, really. I thought I'd keep her honest for a bit. Has a lovely
hat, though, if I do say so myself."

"Huh? Wait a minute," objected Kyoko. "I thought your whole /deal/
was knowing the future. So why?"

"Why would I want to have a conversation where I don't already know
how it ends?" asked Oriko. "What a terrible thought! I must just like
a challenge. Perhaps I'm some sort of a masochist."

"A masochist, eh? Can't say I'd be surprised, with some of the company
around here."

"Oh my. How do the cool kids say it these days, now? /Sick burn/,
Sakura-san. But perhaps you'll fit in! We could find room here for a
juvenile delinquent with a death wish."

"Death wish! I'm still alive, ain't I?" she demanded with a glower.

"Ah, that's right, I'm sorry. In the interests of group harmony, I
should refer to it as a Tendency to Thrill-seeking behavior."

"Okay, do you just spy on all our team meetings?" asked Kyoko, a
little annoyed.

"I prefer to spend my attention on matters that shape the future of
humanity, affairs of truly earth-shattering importance. Do you fancy
your team the center of the universe?"

"No, I think you're a little bit full of it, and a petty eavesdropper,"
said Kyoko, dismissively.

"Well, you're be wrong."

"/Definitely/ an eavesdropper, though."

"You're wrong about the Mitakihara Four. You are /definitely/ the
center of the universe. I've checked. Akemi-san, perhaps, slightly
more than the rest of you."

"Like hell we are," said Kyoko. "Besides, it's only /three/ of us now.
Two and a half, maybe, if I'm taking a vacation."

Oriko's smile dropped. "Yes, how lovely, a vacation! And to think, you
can take as many as you like, wander through the world as you will,
heedless of demons and other girl's territory, fearless! Fate is on
your side, Kyoko. Did it ever cross your mind to ask the oracle how
long you would live, how you were fated to die?  Because she really
can't tell you. You're /special/."

"Like hell I am," Kyoko retorted. Wait - she was repeating herself.
"What is this? Are you trying to butter me up to sell me on some sort
of a contract? Been there already; thanks."

"Simply put, Sakura-san, I am jealous. I've seen some of the ideas
that the future has in store for me. Now, this may make me a bit of a
sentimentalist, but I thought the one where little Yuma seized my
tools, betrayed me, staged a demon attack and joined /your/ team was
particularly compelling."

-----

Yuma played by the koi pond while her two onee-chans had an important
conversation. She was entertaining mixed feelings on the matter. Oriko
had promised that Kyoko-onee-chan would really like her and they'd be
very good friends and do lots of fun together. But when she showed up
she said she'd do mean things to Oriko. But maybe she didn't mean it.
And she liked the garden.

But she had really wanted to take Kyoko to her magical realm so they
could play together and have lots of fun, and that was kind of ruined.

She poked at surface of the fish-pond like a bored cat. /Which is
good/, she considered, /because my costume is like a cat, and so
there's syn.../ syner-somethings, or so Oriko had said, /and it makes
your magic happy/. Then you could do better enchantments. And Yuma was
going to be the bestest enchantress ever. Oriko had promised.

She also promised was going to be a lot of hard work, though. This
wasn't as fun. She swatted at the surface of the pond in
annoyance. /Splash./

"Hey," said a fish in the koi pond. "Stop that. I'm trying to
rehearse."

"I'm sorry!" said Yuma. She stopped.

"It's too late now," said the fish. "You've broken my concentration."

Something seemed a little bit off.  Granted, fish were not normally
supposed to talk, but this was a magic garden, so while it wouldn't do
to ask too many questions, it wouldn't do to ask too few, either. Not
for a big enchantment, anyway.

"It looked like you were just going in circles."

"Yes, and I lost count. Round and round and round she goes!" said the
fish. Or was she a mermaid? It was hard to tell, looking at her; she
was more like a shadow than a proper shape. "Where she'll stop, nobody
knows!"

"What's your name?" she asked the shadow of a fish.

"Call me D-ko. Do you think I've done enough circles?"

"How many is enough?"

"As few as eternity, as many as the embryo of philosophy.
Counter-clockwise, of course."

Yuma pondered. "That sounds like a lot more circles than I saw."
Eternity seemed like it would be a lot of circles.

"Maybe if I go faster, then," said D-ko.

"Slow down, you'll make a whirlpool," objected Yuma. The water was
whirling about already, and Yuma did /not/ like the look of it.

"Ah, it is empty motion! Just empty motion!" cried the fish, whirling
around at a most furious pace.

Yuma backed away from the koi pond. She didn't want to get sucked in
by a whirlpool. It seemed like a good way to get wet. Best to go back
to Oriko. It should be just around the next corner ...

-----

Kyoko was regretting having come, but was trying to keep her cool, at
least until she was done eating. The food was her excuse for coming,
too, and she didn't want to give Mami and Homura something to gloat
about. The conversation had degenerated, however.

"I won't deny it for a moment," said Oriko, replying to a point Kyoko
had made about Yuma. "They are all absolutely terrible role models for
her."

"I'm surprised an ojou-sama like yourself would even hang around with
that crew." she said. "How'd you convince /any/ of them to join a
team? Especially Hinata Aina. More importantly, /why?/"

Oriko paused.

"You know, for all our conversation the other day," she finally said,
"there is one thing you never really answered. Whether you really
believe God is real, or if you just go back for other reasons."

"Truth?" asked Kyoko. "I'm kinda taking it a day at a time on the
matter."

"Is today one of those days?"

Kyoko took a sip of tea. "Well, there's a cute little girl who /isn't/
in nearly as much trouble as I thought she might be. I'm giving it a
definite Maybe right now."

"I see," said Oriko.

"What about it?" asked Kyoko.

"Tell me, Sakura-san. When God decided to save the world, where did he
begin? Did he by saving the nobility? The pretty princess ojou-samas
with nice clothes? The politician's daughters?" She looked Kyoko in
the eye. "Or did he start by making friends with the thugs, the
prostitutes, and the rough men who slept out in the fields with the
sheep?  Did he come to save the prosperous, or the insane and broken
people?"

Kyoko blinked. A dozen different replies leapt to mind, but they were
all half-formed, and most of them ... most of them were probably
better arguments /for/ Oriko here than against her, if you got down to
it. /Damn it/, she thought. She was supposed to be good at this stuff,
but she was /badly/ out of practice. More importantly, it was all
backwards. /She/ was supposed to be the one on that side of the
argument.

In the daze of her confusion, Oriko pressed her argument.

"Consider little Yuna-chan. Her father was going to sell her to the
Yakuza. We saved her. Before that, she was abused. Her mother would
sometimes burn her face with cigarettes. On the forehead, under her
bangs, so no one would see. And we stopped them. We kept Yuma-chan
safe," said Oriko. "Now, the question I have for you is this: What if
Yuma-chan were not so cute? What if she were a little older? Suppose
she had an attitude. When would you say that she no longer deserves a
second chance at life?"

/Ah/, thought Kyoko, /the Devil himself can quote scripture, but.../
/damn, how do I put it?/

Oriko was finishing her argument. "If God were to save only pure and
perfect people, if the world only had room for such as these, the only
place for me would be at my father's side, spending the rest of my
decades in prison."

"You know," said Kyoko, picking her final approach to the argument,
"there's something to that. But the idea of being /saved/ is that you
work yourself to, like, /stop sinning/. You don't threaten people and
tell them you're going to be running their spleen through a cheese
grater."

"Oh dear," said Oriko. "That would have been Kirika-chan, then,
wouldn't it."

"That's the one. Where is she, anyway?"

"She's /out/, at the moment. For what it's worth, I'm working hard to
keep her out of trouble, /and/ helping people."

"Uh-huh. Sure."

"In the beginning," said Oriko, "Kirika and I were chronically short
on grief cubes and did what we had to, to keep alive. And you or
anyone would have done the same, and you know it. It's different
now. We have a nearly full team, we have Yuma-chan is here to help the
fighters recover. We hunt the demons that other teams would have never
noticed, and stay out of the way. We are prosperous and efficient. The
time for viciousness and fighting other teams is behind us. We have a
sustainable cycle, and make a tidy little profit. I forecast the demon
spawns, the hunters track them down, and Yuma keeps us well. We step
on fewer ties."

"Forecasts, huh." Kyoko swallowed some donabe. "That sounds pretty
useful." She pondered a little.

"Yes, it's an excellent scheme," said Oriko. "And it works, and I can
take it further. I'm hoping to cooperate with other teams, trade
information for cubes. I could easily double what magical girls
harvest in Mitakihara. Unfortunately, it all runs through me."

"What's unfortunate about that?" asked Kyoko.

"I only have so much attention," said Oriko, "and saving the magical
girls of Mitakihara is not enough. I intend to save the whole world,
not just the part where I live. What we /really/ need is statistical
modeling, something we can do without magic. It's frustrating, though.
I've seen it in action, but I don't understand it well enough to
re-create it here."

"Wait a second," said Kyoko. "You can /do/ that? Predict demon spawns
with... statistics?"

"In theory. Demons feed on human emotions, so it's essentially applied
psychology and demographics."

"Huh," said Kyoko. "That's ... a really neat idea."

"Oh, that's /Akemi-san's/ idea. I'm just stealing it. But I don't know
quite enough math to make it work. Of course, /she/ doesn't know
enough yet either."

Kyoko looked at Oriko askance. "So let me get this straight. You can
see the future, but you anything about it because you /don't know
enough math/?" she inquired, on the edge of laughter. "That could be
the funniest thing I ever heard."

Oriko grinned. "You think statistics are bad? Three words for
you. /Quantum field theory/."

"Aw, /hell/ no."

"/I have Feynman diagrams on my writing desk right now./"

Kyoko shuddered. "I don't even know what that /means/ and I want
nothing to do with it."

"And that's just the start. I've been copying engineering diagrams and
schematics from memory for a /month/."

"Wait, schematics?" asked Kyoko. "You're trying to invent something
from the future?"

"It's a long story," said Oriko. "The gist of it is that I'm trying to
invent something so that /I don't have to do this anymore./ But it
gets worse before it gets better." She pressed her hands together for
a moment.  "Worth it, though." She smiled.

"What's the payoff?" asked Kyoko.

The smile dropped.

"It's ... an end to a very bad business, hopefully," said Oriko. "I
... shouldn't say, not right now."

Something about her manner seemed familiar. /She's a lot like
Akemi-san/, realized Kyoko, /when you get too close to one of her
little secrets/.

Kyoko's thoughts were interrupted Yuma as returned, out of
breath. "Kyoko-onee-chan!"

"Hey, squirt," said Kyoko, "what's up?"

"I was at the pond and I talked to the fish and she was swimming
around in circles and she said, she said -"

"Wait, the fish talked?" asked Kyoko.

"What part of /magical realm/ don't you understand?" asked Yuma.
"Anyway she was going /way too fast/ so I came back but I got lost on
the stairs on the way back."

Kyoko glimpsed in the direction Yuma had come from.

"I don't see any stairs. What kind of a magical realm are you running
here?" asked Kyoko.

"It's a pocket!" said Yuma.

"A pocket?" Kyoko was confused.

"A pocket universe," amended Oriko. "Small worlds like this are
useful, but the space likes to loop back around on itself, and they're
quite sensitive to build-ups of emotional energy... especially with
three magical girls inside them, and not much else."

"You do this often?" asked Kyoko.

"This is Yuma's second time. We practiced before you came. But there's
a rather sophisticated book on the subject of enchantments that will
tell you all about pocket realms. It's an excellent read - one of the
foundational texts on magic, really."

Kyoko considered. "I don't remember /ever/ hearing anything 'bout any
books on mag -- hey! Is this another one of your ... your future
things?!?"

"But of course. It's one of the reasons I'm teaching Yuma-chan all
about magic."

Yuma nod-nod-nodded. "When I grow up I'm gonna be a beautiful
enchantress."

"Izzat so," said Kyoko.

"Mmm-hmm! And we're going to be /best friends/, and go on adventures!"

"Oh. What /kind/ of adventures?" Kyoko asked Yuma, with a wary glance
at Kyoko.

"We can be, we can be, we can be Elite Secret Agents, saving the world
from certain annihil - uh, annihilation, at the hands of an extra - an
extra-terrestial menace!" Yuma beamed.

"Yuma-chan, you're not old enough to be an elite secret agent yet,"
said Oriko.

"I thought you were going to be a beautiful enchantress?" asked Kyoko.

"A f - femme fatale!" said Yuma.

"Does this have anything to do with Mikune-san's little recruitment
pitch, and why she asked me here today?" asked Kyoko.

"Actually, I was hoping to ask you for help with an errand," said Oriko.
"After /that/, we're going to be taking down the Yakuza."

"Taking down the - are you out of your mind??!" exclaimed Kyoko.

"Well, it's another stolen idea, but /you/ came up with this one."

"When did I do /that?/"

"... I want to say, 2040? Maybe 2045? I don't remember the date
specifically," said Oriko.

"In what alternate universe is a magical girl like me still /alive/ in
30 years?" demanded Kyoko.

"/In my universe, Sakura-san/," said Oriko.

-----

In a more northerly portion of Mitakihara, three girls and an
Incubator met on the school roof at the end of class.

"Ahh, good afternoon, Tomoe-senpai, Homura-chan" said Hitomi.

"Good afternoon, Shizuki-san. Welcome to the Mitakihara Three," said
Mami. "We're glad to have you on the team."

"Mitakihara Four," said Homura. "I saw Sakura-san this morning. She
should be here by nightfall... well, probably, anyway."

"Probably?" inquired Mami.

"She's having /dinner/ with /Mikune Oriko/," said Homura.

"So she might be late?" asked Hitomi.

Mami and Homura glanced at one another.

Kyubey piped up from his perch on Hitomi's shoulder. "The Southern
Group have a history of conflict, especially with the Mitakihara
Four. I believe miss Akemi is concerned for miss Sakura's safety."

"Since you already know about Sayaka-chan," said Mami to Hitomi,
"there's no point in candy-coating it. Magical girls can die in
combat. In fact, it's quite common. It's one reason why we have
teams. And it's not just a question of fighting demons; teams fight
each other over territory. Oriko's team is notoriously violent.
They've ganged up on girls, stolen their grief seeds, and left them to
die at the hands of demons. They've given a lot of groups a lot of
trouble, us especially."

Shizuki Hitomi nodded, solemnly. "Oh."

"I thought you said you wouldn't candy-coat it," said Homura. "I have
no doubt that they have killed girls with their own hands."

Mami sighed. "Right. I wouldn't doubt it."

"Kyoko-chan has been on a reckless streak since Sayaka-chan met with
her untimely end," explained Homura. "While the rest of us had a fine
working relationship with her, Sayaka was perhaps the first person she
had gotten close to in a rather long time, despite their conflict of
personalities - or perhaps, /because/ of it. It culminated in Kyoko
leaving town, under the auspices of 'wandering the wilderness'. But
it's not safe to be a lone wolf, as a magical girl, especially not in
someone else's territory."

"Being part of a team is what keeps us alive," said Mami, "especially
when you're new. So it's very important. Fortunately, we're quite
friendly - even Akemi-san! She's just intense."

"We are also understaffed, with or without Kyoko-chan." added Homura.

Mami nodded. "So we're very glad to have you."

"Oh, thank you so much," said Hitomi. "I'll work hard to do my best."

"That's the spirit," said Mami. "Your magic will generally teach you
the basics of how to fight. What it won't really teach you is tactics,
and how to work with someone else. Which brings me to the next
point. We're all on the same team here, so we're kind stuck with
another whether we like it or not. And we're going to go out there,
every night, and put our lives into each others' hands. So it's
important not to make this any harder than it has to be. We /need/ to
get along with each other; we simply can't afford to fight with
ourselves."

"To be fair," said Homura, relaxed against the wall and idly leafing
through a mathematics textbook, "a magical girl /can/ take on demons
by herself and win, almost every single time. But do not let that fool
you into complacency. But when there is only one of you, it likewise
only takes one mistake to die, and every fight is an opportunity to
make that mistake. To leave your team is to invite death."

Mami nodded. "We place a lot of value on group harmony. You'll hear us
say it a lot."

"In order to survive," said Homura, "we must accept and value each
other, even as flawed and fallen people. And in order to thrive must
put aside our differences and be fast friends. The brutal reality of
our shared fate will put to lie many conceits and fantasies, but in
one, we can yet find solace: that no matter what, our strongest arms
in any fight are the sword of Love, the shield of Hope, and the armor
of Friendship." She closed her book.

"Oh my, Akemi-san," said Mami. "That's ... that's quite lovely."

"It's harsher than it sounds. Not everyone can handle the true meaning
of friendship. May the goddess preserve you, that you not be put to
the test."

"The goddess?" said Hitomi? "Oh -"

"In the interest of group harmony," said Mami, "we do not tease
Akemi-san about her beliefs, and cherish them as part of her
irreplaceable character, accepting her /unique/ blessings with grace."

"Ah, um ..." Hitomi made a face. "Thank you, Akemi-san."

"Please, Hitomi-chan. We are friends now. Soon, we will be /close/
friends. This is my friendly disposition, I assure you."

"... Homura-chan?" asked Hitomi, tentatively.

Homura actually smiled. "Thank you, Hitomi-chan. You will be in good
hands here."

-----

Oriko pushed aside the Feynman diagrams, pulled out a notebook, and
began writing. /Yuma-chan greeted Kyoko with remark about magical
realms./ /Probably imitating Miroko-san./ /Used Kyoko's distress at
this to pitch salvation story for the team.../ The details would take
a while to get down in full, but she should have just enough time
before the others got back.

-----

As the sun was set, Kyoko snuck into the school through one of the
side doors that was easy to unlock with a bit of magic.

She'd promised Oriko to think about it, nothing more, but questions
gnawed at her. The prophetess had gotten under Kyoko's skin. It
was... weird, definitely too much weird stuff going on there. She
wouldn't be comfortable throwing in with a group like that. Besides,
why was she even thinking of it anyway?  She already /had/ a group. It
was high time she got back to them.

Certain remarks kept bothering her, though, like the one about the
Mitakihara Four special to fate. If they were so special, why did
Sayaka have to die? And she just wasn't quite willing to believe it
was a mistake. That girl was playing a long game, and she knew
/exactly/ what she was saying. So what did it mean? Oriko wasn't
implying Sayaka was still alive somehow, was she? No. No way. She
couldn't be. Okay, sure, there was no body. But that's normal.

/You know better, Kyoko/, she told herself. /You shouldn't be letting
your imagination run wild. Get real./

Her train of thought was interrupted by the door to the roof. It was
locked, which was unusual. Not a real obstacle, of course; another bit
of magic and it was open. But it was /never/ locked.

Homura was sitting on the roof, reading, idly stroking the resting
 Kyubey at her side.  Kyoko let the door close itself, with a
 satisfying /clunk/.

"Good evening, Kyoko," said the Incubator, replying to the noise.
"We were wondering when we'd have you back."

"Wondering /if/ we would have you back," added Homura.

"Hey. Am I early or something?" She looked around for Mami. "I mean,
sure, I didn't expect a big welcome-back party or anything, but
locking the door in my face?"

"My apologies. We thought a little bit of extra privacy was in order
today," replied Homura.

"Where's Mami?" Kyoko inquired, taking a look at what Homura was
reading. It was a mathematics text. On a second inspection, it was a
university-level mathematics text, /Intermediate Statistics/.

"She'll be back soon, but she's off playing senpai right now. It's her
favorite."

A sparkle of magic glimmered in the distance. Mami, and ... someone
unfamiliar. Kyoko understood. The Mitakihara /Four/, Oriko had said.

"Oh, that is /cold/, Homura" said Kyoko. "Sign up a new girl to the
team when I'm gone, sure, /fine/. That's the price I pay. But you
could have said something about it this morning."

"Oh, a funny coincidence, that," said Homura, turning a page -

/Incoming!/ came a telepathic shout.

A magical seal formed itself on the roof around them, an elaborate
fractal of delicate green lines and flowers. The surface of the roof
glowed bright white. From the distance, a yellow-green projectile
arced up, heading towards the school, leaving a trail of light behind
it. As it drew closer a /non/-telepathic scream grew louder ...

*pouff*

The energies of the seal released themselves with a flurry of flower
petals, slowing the incoming pair down as they landed on the roof,
tumbling to a stop with a burst of laughter.

"That was a /little/ more energetic than I had in mind," said Mami,
looking at the sky from on her back. "Nice catch, though."

"You said... you said /get us both out of here fast/, and to go
somewhere /safe/," replied Hitomi, picking herself up.

"Well, I suppose you delivered!"

Kyoko stared at the interloper. She had just materialized a tall
silver staff with a great green gem on top to help her to her feet.
With this she wore a flowing, floor-length dress, green with white
trim, that was pleated down the center with extra folds of fabric. The
bodice, set off from the skirt with a ruffly pleplum, was adorned with
military style details: large buttons, decorative waist pockets,
shoulder pads with tassels, and a little cord which made a loop from
her right shoulder to the center of her chest, just below her soul
gem. The top was was sleeveless, but there were showy cuffs at her
wrist, held in place by goodness-knows-what - probably just magic,
actually. Her hair was in an elaborate up-do, just a trifle
dishevelled from her flight, held in place with a five-point /tiara/.

"Sakura Kyoko, this is Shizuki Hitomi," offered Kyubey. "She just made
her contract yesterday evening."

"Oh, I know who /she/ is," said Kyoko. "She's that violin boy's little
princess, isn't she. Isn't that special."

/Special. Favored by fate./ /Not like the girl she's/ replacing,
/obviously./ /Fate would never give a crap about/ her.

"Ah!" said Hitomi, still catching her breath. "Sakura-san. Very
pleased to meet you."

"So tell me, princess, what did /you/ wish for?" demanded Kyoko.

Homura looked up at her, surprised at her tone.

"Uhm," said Hitomi, surprised at the sudden attention, "I just ... I
just wanted to do right by Sayaka-chan."

"Aww /hell/ no," said Kyoko.

"Kyoko?" inquired Mami. "Is everything all right?"

"Hell no," repeated Kyoko. "Fuck this noise."

-----

"Whoops!" said Kirika. "Looks like you're fresh out of grief
cubes!"  She dangled the stolen pouch full of treasure by its strings,
feeling its weight. " A pity! You've been saving up, haven't you? How
/responsible!/ Your mentors would surely be pleased."

"Unfortunately, they can't help you /now/, little bitch," added Hinata
Aina.

Miroko Mikiru gazed into the trapped girl's eyes. "There is no way to
escape my clutches. Your soul is forfeit," she declared, holding aloft
the gem, freshly pried from the girl's costume. She fended off a few
more attempts at biting and jumped back.

Nakanishi squirmed in panic and in pain. "What are you ... what are
you /doing?/" This was bad. She was completely at their mercy and, by
all rights, ought be dead by now. That she somehow /wasn't/ (and was,
instead, merely separated from her soul gem and trapped in Mikiru's
ice cube prison up to her elbows) was perhaps /more/ distressing than
the alternative. And the grief cubes - if it were just hers, that
would be one thing, but Nagisa-chan had been so generous with them.
Perhaps if she could free just one hand...

"It's just what she said," Kirika explained, nonchalantly. "Your soul
is forfeit. It belongs to us now." Kirika /liked/ explaining. It was
so much fun.

"I wonder what Oriko-san wants to do with it," said Aina, grinning. "I
can't even begin to imagine. The possibilities are endless."

"Well, regardless," said Kirika. "It's the /soul/ she wants; we can
just leave her /body/ here. We definitely don't need /that/."

"You know," said Aina, looking out the window, "there are boats out
there in the park."

"What ... what does that have to do with anything??" asked Nakanishi,
unable to concoct an appropriately depraved nautical scenario.

"I'm thinking, Viking funeral," replied Aina. "We can do burning /and/
drowning at once. A beautiful way to go. Sheer poetry."

"No," declared Mikiru. "The ice would float. Or it would melt, and she
would go free. Besides, it would drain her gem, and we want it
intact. You can do it to dispose of the body, though. I will go on
ahead with the soul."

"What do you mean?" demanded the prisoner.

Kirika leaned her back against the ice cube as Mikiru strode out of
the building. "Listen. What's-yer-name. You're pretty new to the
magical lifestyle, right? So I'm guessing your friends never told you
how if a magical girl is more than 100 meters from her soul gem, her
body goes limp, and she blacks out?"

"What?!? That's ... that's crazy. Why would that happen?"

Kirika smiled. "Because it's your /soul/, silly!"

While Nakanishsi's eyes went wide in horror, Kirika reached out and
put a finger to the trapped girl's nose. "Boop!" Then the body went
limp.

"A classic performance," opined Kirika, with a golf clap. "The look on
her face!"

"I'll go take care of the body," said Aina. "Don't you have an
appointment?"

"Crap," said Kirika. "What time is it?"

-----

When Kirika arrived at her appointment - on a rooftop, several miles
away from the school - she found Kyoko was sitting by herself, looking
out over the city. It looked she was pretty bothered about something.
But the redhead interrupted her seething to whirl about and point a
spear at her her neck.

"Hey, cool it, pocky-brains," said Kirika. "I come in peace."

"Like hell you do," said Kyoko.

"Got something for you from Oriko." She tossed a small pouch to Kyoko,
and it landed at her feet. "Payment up front. No strings attached.
Except the strings of fate, obviously. Always got those."

"I told her I'd /think/ about working with her."

"Yeah, well, you just thought about it, didn't ya, so now I'm here,"
said Kirika. "Got some more things for you, too."

"Your boss couldn't be bothered to come out here herself?" asked
Kyoko.

Kirika laughed. "That's not how it works, new girl. Everything's all
planned out in advance, so that Oriko can check that it all still
works. You'll never talk with her /during/ a mission. That could mess
it up."

Kyoko bent down, cautiously, to pick up the sack. That was... a very
good number of grief cubes, actually.

"I guess you have my attention. What's this errand?"

"Deliver a letter," said Kirika, "and make two purchases at a certain
convenience store."

"All this to play errand girl? What's the catch?"

Kirika reached out and offered Kyoko a slim envelope. She accepted it,
warily, peeked inside.

"What is this? Plane tickets?"

"You're going to Amsterdam."

"Like hell I am! Hell, I don't even have a passport."

Kirika pulled out a larger envelope. "Sure you do. It was sitting in a
fire safe in a church in Kazamino."

Kyoko snatched it, angrily. "What the hell? You were going through my
stuff?"

"Could be," shrugged Kirika. "You kind of just left it there, though,
you know? Didn't seem like you cared for it that much."

"Why Amsterdam?" demanded Kyoko.

"How's your English?" asked Kirika.

"It's crap. What does that have to do with anything?"

"They get lots of tourists there and they're pretty good with
English. How's your French? German? Any better?"

"Hell no," said Kyoko.

"Well there you go."

Kyoko rummaged around a bit and extracted a stack of bills from the
envelope, euros, mostly fifties. It was a /lot/ of cash.

"Petty cash for expenses," said Kirika. "There's also a debit card,
prepaid; you're supposed to get yourself something nice while you're
over there. Treat yourself, just keep to the itinerary. If anyone
asks, you're doing a self-directed study on cathedral architecture.
There are some on the itinerary, by the way. You take the bullet
train, head back via Paris, swing by Notre Dame along the way."

"What."

"Oh, and you get a gadget. Catch." She tossed Kyoko a small object.

"What's this?" It was a tetrahedron, black, with a white 0 inscribed
on all each face.

"Grief cubes freak out the X-ray machines, so the airport security
wants to go through them all by hand. You put that little toy in with
them and they all disguise themselves as dice." Kirika grinned.
"Pretty neat, huh?"

It /was/ pretty neat. /Elite secret agents, huh?/

"I'll think about it," said Kyoko.

"Better think fast. Flight's in three hours."

"What the hell? Am I supposed to just sleep on the plane?"

Kirika shrugged. "It's what, a twelve hour flight? You were probably
gonna do that anyway. Besides, isn't it supposed to be first class?
That's supposed to help with the grief cubes at security, too. You
get the special line and they don't ask as many questions."

"Holy shit," said Kyoko, checking the ticket again. She looked up at
Kirika. "Seriously. Is all this actually /normal/ for you guys?"

"The cloak-and-dagger? Kind of. It's been getting more fun. This one's
a little over the top, though." Kirika beamed. "The look on your face
is /amazing/."
